const set1Raw = `Sharif and Lana are purchasing a resale home in Barrie, Ontario, for $500,000. Based on the Ontario Land Transfer Tax (LTT) formula in Chapter 3, what is the exact provincial tax they must pay at closing?|$4,475|$6,475|$8,475|$10,000|1|Calculation: 0.5% on first $55k ($275) + 1.0% on $55k-$250k ($1,950) + 1.5% on $250k-$400k ($2,250) + 2.0% on $400k-$500k ($2,000). Total: $6,475. Note: $4,475 is the net after a first-time buyer rebate, which they do not qualify for here.|Ch 3: Mortgages
A client has a gross annual income of $90,000. Their monthly mortgage P&I is $1,900, property taxes are $300, and heating is $100. They also have a $400 monthly car lease and a $150 minimum credit card payment. What is their Total Debt Service (TDS) ratio?|30.7%|31.9%|38.0%|39.3%|3|Monthly Income = $7,500. TDS = ($1,900 + $300 + $100 + $400 + $150) / $7,500 = $2,850 / $7,500 = 38.0%. Distractor 39.3% uses different heating estimates. Distractor 31.9% is the GDS.|Ch 2: Lending
Bryan Lee is meeting with the Bretons. Sonia is pregnant and wants a house, while Max wants a trip to Italy. Bryan asks them to rank these goals in order of importance. This action takes place during which specific step of the Financial Planning Process?|Step 1: Establishing the Relationship|Step 2: Gathering Client Data|Step 3: Analyzing and Evaluating Status|Step 4: Developing Recommendations|1|According to the textbook, 'Prioritizing Goals' is a core activity within Step 2 (Gathering Data), following the initial identification of goals.|Ch 1: Process
A borrower is qualifying for an uninsured mortgage with a contract rate of 3.75%. According to the OSFI 'Stress Test' rules, what is the minimum qualifying rate the lender must use to calculate the debt service ratios?|3.75%|5.25%|5.75%|6.00%|2|The qualifying rate is the higher of 5.25% or the contract rate + 2%. 3.75% + 2% = 5.75%. Since 5.75% is higher than 5.25%, it is the correct rate.|Ch 3: Mortgages
Anthony Novak is applying for a Home Equity Line of Credit (HELOC). His home is worth $400,000 and his current first mortgage balance is $200,000. Under the standard 80% Loan-to-Value (LTV) rule for revolving credit, what is his maximum available HELOC limit?|$120,000|$200,000|$320,000|$80,000|0|Max LTV total = $400,000 * 0.80 = $320,000. Subtract existing mortgage of $200,000. Available HELOC = $120,000. Distractor $80,000 is 20% of value.|Ch 2: Lending
Which of the following scenarios best exemplifies the 'Objectivity' principle of the Code of Ethics?|An advisor discloses that they receive a commission from the recommended fund.|An advisor ensures their personal prejudices against a client's lifestyle do not affect the advice provided.|An advisor maintains the confidentiality of a client's secret business deal.|An advisor completes their annual continuing education credits on time.|1|Objectivity is specifically defined as being intellectual honest and impartial, ensuring personal bias does not influence professional judgment.|Ch 11: Ethics
During a discovery meeting, a client mentions they are 'extremely worried' about a potential stock market crash affecting their retirement date. This information is classified as:|Quantitative Data|Qualitative Data|Regulatory Data|Monetary Data|1|Qualitative data includes subjective information like attitudes, fears, and internal values that cannot be measured numerically.|Ch 1: Process
Janet is comparing two mortgage options for her $100,000 loan at 7%. Option A is a 25-year amortization. Option B is a 15-year amortization. According to the textbook tables, what is the approximate difference in total interest paid over the life of the mortgage?|$25,491|$49,338|$60,785|$110,123|1|Total interest at 25 years = $110,123. Total interest at 15 years = $60,785. Difference = $49,338. Choosing the shorter period saves nearly $50k.|Ch 3: Mortgages
What is the legal status of 'Creditor Life Insurance' offered by a bank compared to 'Personal Life Insurance' owned by the individual?|The individual owns the policy and can name any beneficiary.|The bank owns the policy and the benefit must be used to pay down the mortgage.|The policy is fully portable to any other lender at renewal.|The premiums are tax-deductible for the borrower.|1|In creditor insurance, the lender is the policyholder and beneficiary; the benefit is strictly applied to the debt.|Ch 3: Mortgages
In the communication model, an advisor who is distracted by a loud construction site outside the office is experiencing which type of 'Filter'?|Psychological Filter|Environmental Filter|Physical Filter|Language Filter|1|Environmental filters are external factors (noise, temperature, lighting) that interfere with the transmission of a message.|Ch 1: Process
Which questioning technique is most likely to result in a 'Yes' or 'No' answer, thereby limiting the gathering of qualitative data?|Open-ended questions|Leading questions|Closed-ended questions|Reflective questions|2|Closed-ended questions are used to confirm facts but are less effective for exploring client values or emotions.|Ch 1: Process
A client has $4,000 in monthly essential expenses. Following the textbook's guideline for an 'Emergency Fund,' what is the minimum liquid cash reserve they should maintain?|$4,000|$8,000|$12,000|$24,000|2|The text recommends a reserve of 3 to 6 months of expenses. $4,000 * 3 = $12,000. $24,000 is the 6-month upper limit.|Ch 2: Budgeting
If a client has a 'Variable' rate mortgage with 'Fixed' monthly payments, what happens if the prime rate rises above the 'Trigger Rate'?|The monthly payment increases immediately.|The bank cancels the mortgage.|The interest not covered by the payment is added to the principal balance (Negative Amortization).|The amortization period is automatically shortened.|2|Trigger rates lead to negative amortization, where the loan balance grows because the fixed payment no longer covers the interest.|Ch 3: Mortgages
Which of the following is an example of an 'Integrity' violation under the Code of Ethics?|An advisor recommends a high-commission product that is equally suitable but more expensive than a low-commission alternative.|An advisor forgets to document a client meeting in the CRM.|An advisor is late for a meeting due to traffic.|An advisor is unable to answer a complex tax question immediately.|0|Integrity requires putting the client's interests first. Choosing a product based on higher commission violates this trust.|Ch 11: Ethics
What is the standard 'Probate Fee' (Estate Administration Tax) in Ontario for an estate valued at exactly $50,000?|$0|$250|$750|$1,500|0|In Ontario, the first $50,000 of an estate's value is exempt from probate fees. Over $50k, the rate is 1.5%.|Ch 10: Estate
Which organization regulates the 'solvency' of federally chartered banks and ensures they maintain enough capital to survive a crisis?|CDIC|OSFI|CIRO|FCAC|1|The Office of the Superintendent of Financial Institutions (OSFI) is the prudential regulator responsible for solvency.|Ch 12: Regulation
A client has $100,000 in a savings account and $50,000 in a TFSA GIC at the same bank. If the bank fails, how much is covered by CDIC?|$100,000|$150,000|$50,000|$0|1|CDIC provides $100k coverage per category. Savings (Single Account) and TFSA are separate categories. Total = $150k.|Ch 12: Regulation
Which stage of the Business Cycle is characterized by a peak in interest rates and a subsequent slowdown in consumer spending?|Expansion|Peak|Contraction|Trough|1|At the peak, the economy is 'overheating,' often leading to higher interest rates to control inflation.|Ch 2: Economics
What is 'Active Listening' in the context of Step 2 of the planning process?|Taking verbatim notes of everything the client says.|Filtering out a client's emotions to focus on the numbers.|Listening with the intent to understand and providing verbal/non-verbal feedback to confirm understanding.|Interrupting the client to correct their misconceptions immediately.|2|Active listening requires engagement and feedback to ensure the 'message sent' is the 'message received.'|Ch 1: Process
A borrower is purchasing a $1.2 Million home. What is the minimum down payment they are legally required to provide?|$60,000|$95,000|$240,000|$300,000|2|Mortgage default insurance is not available for homes over $1 Million. A 20% down payment is mandatory. $1.2M * 0.20 = $240,000.|Ch 3: Mortgages
Which life cycle stage is characterized by high income, aggressive debt reduction, and a focus on retirement savings?|Early Career|Accumulation|Consolidation|Decumulation|2|The Consolidation phase (typically ages 45-55) is the peak earning and saving period.|Ch 1: Process
A client has $8,000 in monthly gross income. Their PITH is $2,400. They have no other debts. What is their GDS ratio?|28%|30%|32%|35%|1|GDS = $2,400 / $8,000 = 30%. Distractor 32% is the conventional limit.|Ch 2: Lending
What is 'Asset Allocation's' primary role in a financial plan?|To pick the single best performing stock.|To reduce unsystematic risk through diversification across asset classes.|To ensure the client pays zero tax on dividends.|To predict the next market trough.|1|Allocation determines the long-term risk and return profile by balancing cash, bonds, and stocks.|Ch 7: Investments
Which document provides a legal certification that a Will is the 'last' valid Will and gives the executor authority to act?|Codicil|Letters Probate|Power of Attorney|Mandate|1|Probate is the court process that validates the Will for third parties like banks.|Ch 10: Estate
A client has a 'Standard' mortgage. They wish to 'port' it to a new home. Which condition is usually required?|The client must pay off the existing mortgage and take a new one.|The new home must be in the same province.|The lender must approve the new property and the client must stay with the same lender.|Porting is only allowed for first-time buyers.|2|Porting allow terms to be moved to a new home, but the lender must approve the asset.|Ch 3: Mortgages
What is the 'Rule of 72' result for an investment earning 6% annually?|6 years|9 years|12 years|15 years|2|Calculation: 72 / 6 = 12 years to double the money.|Ch 5: Math
Which 'Step' in the 6-step process involves identifying 'Gaps' between a client's current resources and their future goals?|Step 2|Step 3|Step 4|Step 5|1|Step 3 (Analyze and Evaluate) is where the advisor identifies the 'shortfalls' or gaps.|Ch 1: Process
Which insurance 'Rider' allows a policyholder to buy more coverage at specific ages without providing medical evidence of health?|Waiver of Premium|Guaranteed Insurability Option (GIO)|Accidental Death|Term Conversion|1|GIO is vital for young professionals whose insurance needs will grow regardless of health changes.|Ch 9: Insurance
What is 'Net Cash Flow'?|Total Assets minus Total Liabilities|Gross Income minus Total Taxes|Total Income minus Total Expenses|Savings minus Debt|2|Cash flow is the 'surplus' or 'deficit' after all inflows and outflows for a period.|Ch 2: Budgeting
A client is 65 and has lived in Canada for only 20 years after the age of 18. What is their OAS entitlement?|Full OAS|50% of a full pension|Nothing|A flat $200 per month|1|OAS is pro-rated based on 40 years for a full pension. 20 / 40 = 50%.|Ch 8: Retirement
Which regulator is responsible for consumer protection and ensuring banks follow 'cost of borrowing' disclosure rules?|OSFI|CIRO|CDIC|FCAC|3|The Financial Consumer Agency of Canada (FCAC) handles consumer rights and bank conduct.|Ch 12: Regulation
What is the 'Federal' bottom tax rate for the 2026 taxation year?|10%|14%|15%|22%|1|For 2026, the lowest federal tax bracket is 14%. Distractor 15% is the 2024/2025 rate.|Ch 4: Taxation
An advisor is asked to 'back-date' an RRSP receipt to help a client get a 2025 tax refund. This is a violation of:|The Professionalism principle|The Integrity principle|The Confidentiality principle|The Diligence principle|1|Integrity involves honesty and placing the law and client interest above personal gain or 'favors.'|Ch 11: Ethics
Which mortgage type allows for the most flexibility to pay down the principal at any time without any penalty?|Closed Fixed Mortgage|Closed Variable Mortgage|Open Mortgage|Convertible Mortgage|2|Open mortgages have higher rates but allow for unlimited prepayments.|Ch 3: Mortgages
A client has $5,000 in 'Interest' income. If their marginal tax rate is 40%, what is the federal tax owed?|$150|$200|$400|$500|2|Interest is 100% taxable at the marginal rate ($5,000 * 0.40 = $2,000). (Note: Question assumes federal-only or simplified total for Distractor)|Ch 4: Taxation
What is the 'Nominal' interest rate?|The rate after inflation|The stated or 'face' interest rate|The rate after taxes|The rate on a government bond|1|Nominal is the 'advertised' rate before adjustments for inflation (Real rate).|Ch 5: Math
Which 'Indicator' is the stock market considered?|Leading|Lagging|Coincident|Predictive|0|The stock market often moves 6-9 months BEFORE the actual economy shifts.|Ch 2: Economics
What is 'Suitability'?|Picking the best stock in the market|Matching advice to the client's risk profile and goals|Charging the lowest fee|Working for a reputable firm|1|Suitability is the primary regulatory standard for advisor conduct.|Ch 11: Ethics
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|Mandat de protection (Mandate)|Codicil|Trust|Will|0|Quebec uses the 'Mandate' for handling incapacity.|Ch 10: Estate
What is the RRSP contribution room calculation for 2026?|18% of previous year's assets|18% of previous year's earned income, up to a cap|10% of total net worth|A flat $30,000|1|RRSP room is based on 18% of earned income, capped at the annual maximum ($33,810 for 2026).|Ch 8: Retirement
Which insurance 'Rider' pays the policy premiums if the insured becomes totally disabled?|Accidental Death|Waiver of Premium|Guaranteed Insurability|Term Rider|1|Waiver of Premium keeps the policy in force during disability.|Ch 9: Insurance
A client has $500,000 in a house and $200,000 in a mortgage. What is their 'Equity'?|$200,000|$300,000|$500,000|$700,000|1|Equity = Market Value ($500k) - Debt ($200k) = $300k.|Ch 3: Mortgages
Which stage of the Business Cycle follows a 'Trough'?|Expansion|Peak|Contraction|Recession|0|Expansion is the recovery phase after the bottom (trough) is reached.|Ch 2: Economics
What is 'Inflation'?|A decrease in interest rates|A general increase in prices and a fall in the purchasing power of money|An increase in the value of the dollar|A stock market crash|1|Inflation erodes the real value of money over time.|Ch 2: Economics
A client dies 'Intestate.' What determines how their assets are distributed?|The bank|The provincial succession laws|The federal tax law|The executor's discretion|1|Intestacy triggers the provincial formula for asset distribution.|Ch 10: Estate
Which organization regulates the 'conduct' of mutual fund and investment advisors?|OSFI|CIRO|CDIC|FCAC|1|CIRO (formed from IIROC and MFDA) oversees advisor conduct and suitability.|Ch 12: Regulation
What is the 'Inclusion Rate' for a capital gain in 2026?|25%|50%|75%|100%|1|Only 50% of a capital gain is added to taxable income for individuals.|Ch 4: Taxation
Which document appoints a 'Guardian' for minor children?|Power of Attorney|Will|Codicil|Trust Deed|1|The Will is the only document that can legally appoint a guardian.|Ch 10: Estate
What is 'Asset Correlation' used for?|Calculating total return|Determining how two investments move in relation to each other|Setting the tax rate|Determining the client's age|1|Low or negative correlation reduces total portfolio risk.|Ch 7: Investments
Which ratio measures a client's ability to cover short-term debts with liquid assets?|Current Ratio|Debt-to-Equity|GDS|TDS|0|Current Ratio = Current Assets / Current Liabilities.|Ch 2: Budgeting
What is 'Deflation'?|Prices going up slowly|A general decrease in the price level of goods and services|High unemployment|A drop in interest rates|1|Deflation is the opposite of inflation.|Ch 2: Economics
Which organization manages the 'Consumer Price Index' (CPI)?|Bank of Canada|CRA|Statistics Canada|OSFI|2|StatsCan tracks the basket of goods used for CPI.|Ch 2: Economics
What is a 'LIRA' (Locked-in Retirement Account)?|A type of insurance|A plan used to hold transferred pension funds|A credit card|A legal investment agreement|1|LIRAs hold pension funds that cannot be withdrawn until retirement.|Ch 8: Retirement
Which insurance covers a business if a 'Key Person' dies?|Group Life|Key Person Insurance|Workers Comp|Universal Life|1|Key Person insurance helps the business manage the loss of a vital employee.|Ch 9: Insurance
What is 'Execution' in the context of a Last Will?|The reading of the will|The legal signing and witnessing process|The distribution of money|The payment of taxes|1|A Will must be properly executed to be legally valid.|Ch 10: Estate Planning
What is 'Monetary Policy'?|Tax rate management|Management of interest rates and money supply by the Bank of Canada|Government spending|Corporate law|1|The Bank of Canada uses rates to control inflation.|Ch 2: Economics
Which 'Indicator' predicts future economic activity?|Lagging Indicator|Leading Indicator|Coincident Indicator|Trough Indicator|1|Leading indicators (like stock prices) signal where the economy is going.|Ch 2: Economics
Which type of risk is caused by a change in tax laws?|Market Risk|Interest Rate Risk|Legislative Risk|Inflation Risk|2|Legislative risk is the risk of government rule changes.|Ch 7: Investments
What is 'Real' GDP?|GDP including all sectors|GDP adjusted for inflation|GDP before taxes|GDP of the housing market|1|Real GDP accounts for inflation to show true economic growth.|Ch 2: Economics
Which stage of the 6-step process involves 'KYC' (Know Your Client)?|Step 1|Step 2|Step 4|Step 6|1|Step 2 (Gathering Data) is where the deep KYC profile is built.|Ch 1: Process
Which insurance 'Rider' pays the premiums if the insured becomes disabled?|Accidental Death|Guaranteed Insurability|Waiver of Premium|Term Conversion|2|Waiver of Premium keeps the policy in force during disability.|Ch 9: Insurance
What is the 'Federal' bottom tax rate in 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is 14%.|Ch 4: Taxation
A client has a $300,000 mortgage. They win $50,000 and pay it directly toward the principal. What is the primary impact?|The monthly payment decreases immediately|The interest rate is lowered|The amortization period is significantly shortened|The bank will charge an IRD penalty|2|Principal prepayments shorten the life of the loan.|Ch 3: Mortgages
What is the 'Nominal' rate of a loan?|The rate after inflation|The stated or 'face' interest rate|The rate after taxes|The rate on a car loan|1|Nominal is the advertised rate before adjustments.|Ch 5: Math
If a client dies with no Will and no heirs, what is the term for the government taking the assets?|Probate|Escheat|Intestacy|Codicil|1|Escheat is the last resort for ownerless property.|Ch 10: Estate Planning
What is the 'Liquidity' of a private family business?|Very High|Moderate|Very Low|Same as a stock|2|Private businesses are illiquid and hard to sell quickly.|Ch 7: Investments
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|Mandat de protection (Mandate)|Codicil|Trust|Will|0|Quebec uses the 'Mandate' in case of incapacity.|Ch 10: Estate Planning
Which regulator monitors 'Investment Advisors' and 'Mutual Fund' dealers?|OSFI|CIRO|CDIC|FINTRAC|1|CIRO (formed from IIROC and MFDA) handles dealer conduct.|Ch 12: Regulation
A client has a $1,000 non-refundable tax credit. They are in a 40% tax bracket. How much tax do they save?|$150|$400|$600|$1,000|0|Federal non-refundable credits are calculated at the lowest bracket rate (15% or 14% in 2026).|Ch 4: Taxation
If you are 45 and want to retire at 65, what is your 'Time Horizon'?|10 years|20 years|45 years|65 years|1|65 - 45 = 20 years.|Ch 7: Investments
What is 'Diversification'?|Buying only one company|Spreading money across many different companies and sectors|Investing only in GICs|Avoiding all stocks|1|Diversification reduces 'Unsystematic' risk.|Ch 7: Investments
Which stage of the planning process involves 'Brainstorming' strategies?|Gather|Analyze|Develop|Implement|2|The 'Development' phase is the strategy design phase.|Ch 1: Process
What is 'Inflation's' effect on a fixed-income retiree?|It makes them richer|It reduces their purchasing power over time|It has no effect|It reduces their tax bill|1|Inflation erodes the value of a fixed income.|Ch 2: Economics
Which 'Mortgage' term is generally the most expensive?|5-year Fixed|1-year Variable|Open Mortgage|10-year Fixed|2|'Open' mortgages have high rates for maximum flexibility.|Ch 3: Mortgages
What is 'Standard Deviation'?|The average return|A measure of how much a stock's price swings (risk)|A type of dividend|A bank fee|1|Higher SD means higher volatility.|Ch 7: Investments
A client earns $75,000. They have $10,000 in 'Tax Deductions.' What is their taxable income?|$65,000|$75,000|$85,000|$0|0|$75,000 - $10,000 = $65,000.|Ch 4: Taxation
Which document appoints someone to manage your 'money' while you are alive but incapacitated?|Will|Property POA|Personal Care POA|Executor|1|Property POA handles finances for the living.|Ch 10: Estate Planning
What is 'Net Worth'?|Annual salary|Assets minus Liabilities|Cash in the bank|The value of a car|1|Net worth is a 'snapshot' of wealth.|Ch 2: Budgeting
Which 'Benefit' is based on how much you worked and contributed?|OAS|GIS|CPP|Allowance|2|CPP is a 'Contributory' plan.|Ch 8: Retirement
What is the 'Rule of 72' result for 4% return?|12 years|15 years|18 years|72 years|2|72 / 4 = 18 years to double.|Ch 5: Math
Which insurance is a 'Lump Sum' upon diagnosis of cancer?|Life|Disability|Critical Illness|Dental|2|Critical illness pays out a survival benefit.|Ch 9: Insurance`;

const set2Raw = `Isaac Sinclair receives a gross bonus of $5,000 in 2026. If his marginal tax rate is 35% and he chooses NOT to contribute to an RRSP, how much 'After-Tax Cash' will he actually receive?|$1,750|$3,250|$4,250|$5,000|1|After-tax cash = Gross ($5,000) - Tax ($5,000 * 0.35 = $1,750) = $3,250.|Ch 4: Taxation
Adam contributes $10,000 to a spousal RRSP in the name of his spouse, Roger, in February 2026. If Roger withdraws the full $10,000 in December 2027 to pay for a trip, who must report this as income?|Roger, because the plan is in his name.|Adam, because the withdrawal occurred within the '3-year' attribution window.|The income is split 50/50 between Adam and Roger.|The withdrawal is tax-free because it is a spousal plan.|1|Withdrawals from a spousal plan in the year of contribution or the next two calendar years are attributed to the contributor (Adam).|Ch 4: Taxation
Casey has medical expenses of $1,000 in December 2025 and $800 in February 2026. His net income is $40,000. To maximize his non-refundable credit, what is the best strategy according to the '12-month period' rule?|Claim $1,000 in 2025 and $800 in 2026 separately.|Select a 12-month period (e.g., Mar 2025 to Feb 2026) to group the $1,800 together.|Claim only the $1,000 as medical credits cannot span calendar years.|Wait until 2027 to claim both amounts.|1|Taxpayers can select any 12-month period ending in the taxation year to maximize the claim over the 3% income floor.|Ch 4: Taxation
Don and Mary Sundridge have two children. Don earns $120,000 and Mary earns $35,000. If they incur $8,000 in childcare expenses, who is generally required to claim this deduction?|Don, because he is in a higher tax bracket.|Mary, because the deduction must be claimed by the lower-income spouse.|Either spouse can claim the deduction.|The child with the lowest income claims it.|1|The textbook states that child care expenses must generally be claimed by the spouse with the lower net income.|Ch 4: Taxation
A client has $10,000 in capital gains and $14,000 in capital losses in 2026. What is the 'Net Capital Loss' that can be carried back or forward to offset other capital gains?|$0|$2,000|$4,000|$7,000|1|Net Capital Loss = ($14,000 - $10,000) * 50% inclusion rate = $2,000.|Ch 4: Taxation
Jill is in a 'Defined Contribution' (DC) plan, while Maxie is in a 'Defined Benefit' (DB) plan. According to Chapter 6, who bears the primary 'Investment Risk' for their future retirement income?|Jill bears the risk in her DC plan.|Maxie bears the risk in her DB plan.|The employer bears the risk for both Jill and Maxie.|The Government bears the risk through the CPP.|0|In a DC plan, the final benefit depends on investment performance, placing the risk on the employee (Jill).|Ch 6: Retirement
Cecilia has resided in Canada for exactly 25 years after the age of 18. If the full OAS pension is $700/month, what is Cecilia's monthly OAS entitlement?|$175.00|$350.00|$437.50|$700.00|2|OAS is pro-rated at 1/40th for each year of residence. (25/40) * $700 = $437.50.|Ch 6: Retirement
An individual has a net world income of $115,323 in 2026. Given the OAS recovery tax threshold is $95,323, what is the 'Clawback' amount they must repay?|$2,000.00|$3,000.00|$15,000.00|$20,000.00|1|Clawback = (Income - Threshold) * 15%. ($115,323 - $95,323) * 0.15 = $3,000.|Ch 6: Retirement
A client withdraws $60,000 from their RRSP under the 'Home Buyers Plan' (HBP) in 2026. When is the first of their 15 equal annual repayments due?|In 2026 (the year of withdrawal).|By the 60th day of 2027.|In the second calendar year following the year of withdrawal (2028).|Only when the home is sold.|2|HBP repayments must begin in the second calendar year following the year of withdrawal.|Ch 6: Retirement
A parent contributes $2,500 to a child's RESP in 2026. What is the maximum Canada Education Savings Grant (CESG) they will receive for this contribution?|$250|$500|$1,000|$7,200|1|The basic CESG is 20% of the first $2,500 contributed annually ($500).|Ch 5: Investments
If a client has a 'Marginal Tax Rate' of 40% and receives $1,000 in 'Interest' income, how much 'After-Tax' cash will they keep?|$400|$600|$860|$1,000|1|Interest is 100% taxable at the marginal rate. $1,000 - ($1,000 * 0.40) = $600.|Ch 4: Taxation
An investor in a 45% marginal bracket receives $1,000 in 'Eligible' Canadian dividends. With a 38% gross-up, what is the 'Taxable Income' added to their return?|$1,000|$1,380|$1,450|$2,000|1|Gross-up: $1,000 * 1.38 = $1,380.|Ch 4: Taxation
Which of the following is a 'Non-Refundable' tax credit in 2026?|GST/HST Credit|Canada Child Benefit|Basic Personal Amount|Working Income Tax Benefit|2|Non-refundable credits reduce tax to zero but do not generate a refund.|Ch 4: Taxation
A client moves 150km for a new job. They sell their home for a $50,000 loss and pay $20,000 in real estate commissions. What can they deduct as 'Moving Expenses'?|The $50,000 loss only.|The $20,000 commission only.|Both the loss and the commission.|Neither.|1|Moving expenses include commissions on the sale of a home, but not the actual loss on the sale.|Ch 4: Taxation
What is the 'Rule of 72' result for an investment expected to earn 9% annually?|4 years|6 years|8 years|9 years|2|Calculation: 72 / 9 = 8 years.|Ch 5: Math
Which investment has the highest 'Interest Rate Risk' if rates rise by 1%?|A 30-day T-Bill.|A 5-year GIC.|A 20-year Government Bond.|A Daily Interest Savings Account.|2|Long-term fixed-income securities are the most sensitive to rate changes.|Ch 5: Investments
An employee is 65 and continues to work while receiving CPP. They choose to continue contributing to CPP. What benefit are they earning?|OAS Supplement.|Post-Retirement Benefit (PRB).|GIS Bonus.|Early Access Credits.|1|Working CPP recipients under 70 can earn the PRB to increase their future pension.|Ch 6: Retirement
An investor holds a stock with an ACB of $10,000 and sells it for $16,000. What is the 'Taxable Capital Gain'?|$6,000|$3,000|$1,500|$8,000|1|Gain is $6,000. The taxable inclusion rate is 50% ($3,000).|Ch 4: Taxation
A client has $2,000 in 'Non-Refundable' tax credits. If the bottom federal tax rate is 14%, how much tax liability do these credits eliminate?|$280|$800|$2,000|$0|0|Non-refundable credits are calculated at the bottom bracket rate. $2,000 * 0.14 = $280.|Ch 4: Taxation
What is the primary risk of holding a large amount of cash during a period of 5% annual inflation?|Market Risk.|Liquidity Risk.|Purchasing Power Risk.|Credit Risk.|2|Inflation erodes the real value of money over time.|Ch 8: Risk
What is the 'Prescribed Rate' loan used for in income splitting?|To lower a client's mortgage rate.|To lend money to a spouse for investment without attribution rules applying.|To buy a car.|To pay for university.|1|Loans at the prescribed rate allow income to be taxed in the lower-earning spouse's hands.|Ch 4: Taxation
Which of the following is 'Excluded' from Total Income on a Canadian tax return?|Lottery Winnings.|Tips and Gratuities.|Rental Income.|Stock Dividends.|0|Lottery winnings and most gifts are non-taxable in Canada.|Ch 4: Taxation
A client is 71 on December 31, 2026. They must convert their RRSP to a RRIF. If they have $100,000, what is the mandatory minimum withdrawal for the next year?|$0.|A percentage based on their age (e.g., 5.28%).|The full $100,000.|A flat $10,000.|1|RRIF withdrawals are a mandatory percentage based on the plan's January 1st value.|Ch 6: Retirement
Which insurance policy pays a lump sum benefit to the insured upon surviving a specified illness such as cancer?|Life Insurance.|Disability Insurance.|Critical Illness Insurance.|Health Insurance.|2|Critical Illness insurance is a survival-based benefit.|Ch 8: Risk
What is 'Asset Correlation' used for in Chapter 5?|Calculating the total return of one stock.|Determining how two different investments move relative to each other.|Setting the tax rate on bonds.|Determining a client's age.|1|Correlation helps reduce portfolio risk through diversification.|Ch 5: Investments
Which stage of the Business Cycle has high unemployment and negative GDP growth?|Peak.|Trough.|Expansion.|Recovery.|1|The Trough is the bottom of the cycle, often characterized by high unemployment.|Ch 2: Economics
An investor receives $500 in interest within their TFSA. How much tax is owed on this income?|$0|$75|$150|$200|0|Income and gains earned inside a TFSA are 100% tax-free.|Ch 5: Investments
A client has a $300,000 mortgage on a $500,000 house. What is their 'Equity'?|$200,000|$300,000|$500,000|$800,000|0|Equity = Market Value ($500k) - Debt ($300k) = $200k.|Ch 3: Mortgages
Which organization regulates the 'solvency' of Canadian banks and insurers?|CIRO.|OSFI.|CDIC.|FCAC.|1|OSFI monitors the financial health (solvency) of institutions.|Ch 12: Regulation
If a client has a 5-year fixed mortgage at 3% and current 5-year rates are 5%, what is the likely penalty to 'break' the mortgage?|The Interest Rate Differential (IRD).|3 months of interest.|A flat $1,000 fee.|No penalty.|1|When market rates are higher than the contract rate, banks usually charge 3 months interest.|Ch 3: Mortgages
An investor in a 45% marginal bracket has a $10,000 capital loss from a previous year. In 2026, they have $8,000 in interest income and $6,000 in capital gains. What is their 'Taxable Income' from these two sources after applying the loss?|$0|$4,000|$8,000|$10,000|2|Capital losses can only offset capital gains. $6,000 gain - $6,000 of the loss = $0 taxable gain. The $8,000 interest remains 100% taxable. Total taxable income = $8,000.|Ch 4: Taxation
A client moves 250km for a new job. They earn $5,000 at the new location in 2026 but incur $12,000 in eligible moving expenses. How much can they deduct on their 2026 return?|$0|$5,000|$12,000|$7,000|1|Moving expenses are deductible only up to the amount of income earned at the new location. The remaining $7,000 can be carried forward to 2027.|Ch 4: Taxation
Which of the following would be considered an 'Allowable Business Investment Loss' (ABIL) rather than a standard capital loss?|A loss on the sale of shares in a public blue-chip corporation.|A loss on a loan to a 'Qualified Small Business Corporation' (QSBC) that has gone insolvent.|A loss on the sale of a personal-use vehicle.|A loss on a government bond due to rising interest rates.|1|An ABIL results from the disposition of shares or debt of a QSBC and can be used to offset ALL types of income, unlike standard capital losses.|Ch 4: Taxation
A client pays $2,000 in annual interest on a loan used to purchase a vacant lot for future development, but the lot currently generates zero income. Is this interest deductible?|Yes, interest is always deductible if the intent is to make a profit.|No, interest on a loan for a vacant lot is generally not deductible unless it produces income.|Only if the client is a real estate agent.|Only if the client has a 40% marginal rate.|1|The textbook logic for carrying charges specifies that interest is deductible only when borrowed for the purpose of earning income (interest, dividends, or rent).|Ch 4: Taxation
A university student has $10,000 in tuition fees but only needs $2,000 to reduce their own tax to zero. According to Chapter 4, what is the maximum amount they can 'transfer' to a parent or grandparent?|$0|$3,000|$5,000|$8,000|2|The textbook states that a student can transfer a maximum of $5,000 in tuition amount to a supporting relative.|Ch 4: Taxation
An investor buys a 'Strip Bond' for $700 that matures in 5 years for $1,000. Under the 'Accrual Method' for interest, how must they report the $300 gain?|They report the full $300 as a capital gain in year 5.|They report the full $300 as interest income in year 5.|They must report a portion of the interest annually as it 'accrues,' even though no cash is received.|The gain is tax-free if held to maturity.|2|The accrual method requires taxpayers to report interest annually on investments where interest is not paid out (e.g., strip bonds, compound GICs).|Ch 4: Taxation
A client sells their primary residence for $600,000 (Cost: $200,000). In the same year, they sell a rental property for a $100,000 gain. How much capital gain is reported?|$0|$50,000|$200,000|$250,000|1|The primary residence gain is exempt. The rental property gain of $100,000 is 50% taxable, resulting in a $50,000 taxable capital gain.|Ch 4: Taxation
An investor has a 'Systematic Risk' concern regarding their portfolio. Which of the following strategies would most effectively address this?|Adding more stocks from the same sector.|Diversifying into different asset classes (e.g., adding bonds or gold).|Buying shares in a large, stable utility company.|The risk cannot be eliminated through diversification.|3|Systematic risk (market risk) affects the entire market and cannot be diversified away, unlike unsystematic risk.|Ch 5: Investments
A client wishes to save $20,000 for their child's education in 10 years. If they can earn 6% annually, what is the 'Present Value' (PV) they need to invest today?|$11,167|$12,500|$15,000|$18,800|0|PV = $20,000 / (1.06)^10 = $11,167.90.|Ch 5: Math
If a stock has an expected return of 12% and a 'Beta' of 1.5, what does this imply about its volatility compared to the S&P/TSX Composite index?|It is 1.5 times less volatile than the market.|It is 50% more volatile than the market.|It is guaranteed to return 1.5% more than the market.|It has zero unsystematic risk.|1|A Beta of 1.5 means the stock is 50% more volatile than the market index (Beta of 1.0).|Ch 5: Investments
A subscriber over-contributes $2,000 to an RESP. According to Chapter 5, what is the monthly penalty tax on this excess amount?|$10|$20|$40|$100|1|Excess RESP contributions are subject to a 1% per month penalty tax ($2,000 * 0.01 = $20).|Ch 5: Investments
A 35-year-old client withdraws $10,000 from their RRSP under the 'Lifelong Learning Plan' (LLP) to pay for their own degree. What is the maximum they can withdraw over the life of the plan?|$10,000|$20,000|$35,000|$60,000|1|The LLP limit is $10,000 per year, up to a total maximum of $20,000.|Ch 6: Retirement
An individual is 62 and receives the CPP 'Survivor's Pension' after their spouse passes away. If they also qualify for their own CPP retirement pension, how is the total amount determined?|They receive both pensions in full.|The total is capped at the maximum retirement pension for a single person.|They must choose only one.|The survivor's pension is cancelled.|1|When combining a retirement and survivor pension, the total cannot exceed the maximum single retirement pension.|Ch 6: Retirement
A senior is turning 73 in 2026. If their RRIF is valued at $500,000 on Jan 1st and the withdrawal factor is 5.53%, what is the mandatory minimum withdrawal?|$25,000|$27,650|$40,000|$55,300|1|Mandatory Withdrawal = $500,000 * 0.0553 = $27,650.|Ch 6: Retirement
A client has $100,000 in a Locked-in Retirement Account (LIRA). They are 66 and wish to begin generating income. What must they convert the LIRA into?|A regular RRIF|A Life Income Fund (LIF) or a Life Annuity|A TFSA|Cash|1|Locked-in funds from a pension must be converted into a LIF or an annuity to provide a lifetime income.|Ch 6: Retirement
What is the 'Pension Adjustment' (PA) designed to do?|To increase RRSP room for those with pensions.|To ensure fairness by reducing RRSP room for employees who earn retirement benefits in a workplace pension.|To pay for the administration of the CPP.|To adjust for inflation in the RRIF.|1|The PA represents the value of benefits earned in an RPP or DPSP and reduces the next year's RRSP room.|Ch 6: Retirement
An investor receives a $1,000 dividend from a US-based corporation. How is this taxed on their Canadian return?|With a 38% gross-up and dividend tax credit.|As 100% taxable interest income.|As 50% taxable capital gain.|It is tax-free up to $1,000.|1|Foreign dividends do not qualify for the Canadian gross-up and credit system and are taxed like interest income.|Ch 4: Taxation
Which 'Tax Shelter' allows for the growth of investments to be completely tax-free, even upon withdrawal?|RRSP|TFSA|RESP|Registered Pension Plan|1|Unlike RRSPs, TFSA withdrawals are not reported as income and are 100% tax-free.|Ch 5: Investments
A 68-year-old has lived in Canada for 8 years since age 18. Do they qualify for any OAS?|Yes, a full pension.|Yes, 8/40ths.|No, they must have at least 10 years of residency to qualify for a partial pension.|Only if their income is zero.|2|A minimum of 10 years of residence in Canada after age 18 is required to receive any OAS.|Ch 6: Retirement
What is the 'Death Benefit' provided by the CPP in 2026?|A variable amount based on contributions.|A flat $2,500 payment to the estate.|60% of the contributor's pension.|Nothing.|1|The CPP provides a one-time flat-rate death benefit of $2,500.|Ch 6: Retirement
If a client over-contributes $5,000 to their RRSP, how much of that over-contribution is exempt from the 1% per month penalty tax?|$0|$1,000|$2,000|$5,000|2|There is a $2,000 lifetime allowance for RRSP over-contributions that is not subject to the penalty.|Ch 6: Retirement
A client wants to ensure their 'After-Tax' retirement income is $50,000. If their average tax rate in retirement is 20%, what 'Pre-Tax' income do they need to generate?|$50,000|$60,000|$62,500|$70,000|2|Calculation: $50,000 / (1 - 0.20) = $62,500.|Ch 6: Retirement
Which type of investment is best suited for an RESP with a 2-year time horizon before the child enters university?|Common Stocks|Equity Mutual Fund|GIC or Money Market Fund|Cryptocurrency|2|Short time horizons require safety of principal and high liquidity.|Ch 5: Investments
An investor holds a bond with a 5% coupon. If market interest rates rise to 7%, what happens to the market price of the bond?|It increases.|It decreases.|It remains the same.|It matures immediately.|1|Bond prices have an inverse relationship with interest rates.|Ch 5: Investments
A 65-year-old earns $100,000 in net income. If the OAS clawback threshold is $95,323, what is the 'Net' OAS they keep if the full benefit is $8,000?|$7,300.00|$8,000.00|$7,298.45|$5,000.00|2|Clawback = ($100,000 - $95,323) * 0.15 = $701.55. Net OAS = $8,000 - $701.55 = $7,298.45.|Ch 6: Retirement
What is the maximum annual RRSP contribution room a person can earn in 2026?|18% of earned income, no limit.|A flat $33,810.|The lesser of 18% of 2025 earned income or $33,810.|100% of their salary.|2|RRSP room is the lesser of 18% of the previous year's earned income or the annual dollar limit ($33,810 for 2026).|Ch 6: Retirement
A client's employer matches their 5% contribution to a 'Defined Contribution' pension plan. According to Chapter 6, who is responsible for choosing the investments?|The Employer|The Pension Fund Manager|The Employee|The Government|2|In a DC plan, the employee typically bears the investment risk and chooses from a menu of options.|Ch 6: Retirement
A client is in the 50% marginal bracket and receives a $1,000 'Eligible' dividend. After the 38% gross-up and a combined 25% tax credit, what is the 'Net Tax' they pay?|$150.00|$195.00|$345.00|$500.00|2|Calculation: Grossed-up income = $1,380. Tax at 50% = $690. Credit (25% of $1,380) = $345. Net Tax = $690 - $345 = $345.|Ch 4: Taxation
An investor has a 'High' risk tolerance and a 20-year time horizon. Which asset class does the textbook suggest for maximizing long-term growth?|GICs|Government Bonds|Common Stocks|Savings Accounts|2|Equities (Stocks) historically offer higher long-term returns but with higher volatility.|Ch 5: Investments
Which document is used to 'Rollover' RRSP funds to a surviving spouse without immediate tax?|A Will|A Power of Attorney|A Beneficiary Designation|A Codicil|2|Naming a spouse as the 'beneficiary' or 'successor' allows for a tax-deferred rollover at death.|Ch 6: Retirement
A client pays $6,000 in 'Spousal Support' and $4,000 in 'Child Support' annually. According to the textbook rules in Chapter 4, what is the total amount they can deduct from their total income for tax purposes?|$0|$4,000|$6,000|$10,000|2|Spousal support is generally deductible to the payer and taxable to the recipient, while child support is non-deductible and non-taxable[cite: 13].|Ch 4: Taxation
A parent has contributed $30,000 to their child's RESP over several years. What is the absolute 'Lifetime' maximum in Canada Education Savings Grant (CESG) funds that this child can receive?|$2,500|$5,000|$7,200|$10,000|2|The total lifetime CESG amount for any one beneficiary is capped at $7,200[cite: 13].|Ch 5: Investments
A client withdraws $5,000 from their TFSA in 2026. On January 1, 2027, how much is added to their 'Contribution Room' specifically due to this withdrawal?|$0|$2,500|$5,000|$10,000|2|Withdrawals from a TFSA are added back to the contribution room on January 1st of the following calendar year[cite: 11].|Ch 5: Investments
An investor is in the 45% marginal tax bracket. If they receive a $1,000 'Eligible' dividend, what is the 'Grossed-up' amount they must report as taxable income?|$1,000|$1,150|$1,380|$1,500|2|Eligible dividends from public Canadian corporations are grossed-up by 38% ($1,000 * 1.38 = $1,380)[cite: 13].|Ch 4: Taxation
A client has a net income of $80,000. They have $2,000 in 'Non-Refundable' tax credits. If the bottom federal tax rate is 14%, how much do these credits reduce their 'Tax Payable'?|$280|$800|$2,000|$0|0|Non-refundable federal tax credits are calculated at the lowest tax bracket rate (14% in 2026). $2,000 * 0.14 = $280[cite: 13].|Ch 4: Taxation
Which of the following describes an 'Allowable Business Investment Loss' (ABIL)?|A loss on a blue-chip stock in a TFSA.|A loss on a loan or shares in a 'Qualified Small Business Corporation' (QSBC).|A loss on a primary residence sale.|A loss on a government bond.|1|An ABIL is a specific type of capital loss (50% inclusion) that can offset all types of income[cite: 13].|Ch 4: Taxation
A client moves 150km for a new job. They pay $20,000 in real estate commissions to sell their old home and $15,000 to buy a new one. How much can they deduct as 'Moving Expenses' in 2026?|$0|$20,000|$35,000|Unlimited|2|Moving expenses include both the commission to sell the old home and the legal/tax costs of buying the new one[cite: 13].|Ch 4: Taxation
An individual is 65 years old and has lived in Canada for exactly 15 years since age 18. If the full OAS pension is $700, what is their monthly entitlement?|$175.00|$262.50|$350.00|$700.00|1|OAS is pro-rated based on years of residence. 15 / 40 * $700 = $262.50[cite: 18].|Ch 6: Retirement
A senior earns $110,323 in net income in 2026. If the OAS threshold is $95,323, what is the 'OAS Pension Recovery Tax' (Clawback) they must pay?|$1,500|$2,250|$3,000|$4,500|1|Clawback = (Income - Threshold) * 0.15. ($110,323 - $95,323) * 0.15 = $2,250[cite: 18].|Ch 6: Retirement
A contributor dies in 2026. What is the flat-rate 'Death Benefit' that the CPP will pay to their estate?|$1,000|$2,500|$5,000|$10,000|1|The CPP provides a one-time universal death benefit of $2,500[cite: 18].|Ch 6: Retirement
A 65-year-old decides to delay their CPP until age 70. What is the total percentage increase in their monthly pension?|36%|42%|50%|60%|1|CPP increases by 0.7% per month of delay, which is 8.4% per year or 42% over 5 years[cite: 18].|Ch 6: Retirement
Which document is used to determine the 'Pension Adjustment' (PA) which reduces an individual's RRSP room for the following year?|T4 Slip|Notice of Assessment|T5 Slip|Will|0|The PA is calculated by the employer and reported on the T4 slip[cite: 17].|Ch 6: Retirement
What happens to an RRSP withdrawal of $10,000 if it is NOT repaid within the 15-year Home Buyers' Plan (HBP) window?|The bank charges a 10% penalty.|The amount is added to the taxpayer's income for that year.|The government takes the house.|The amortization is extended.|1|Unpaid HBP installments are included in the taxpayer's income and taxed at their marginal rate[cite: 16].|Ch 6: Retirement
A 35-year-old client withdraws $15,000 from their RRSP under the 'Lifelong Learning Plan' (LLP). What is the maximum they can withdraw over the duration of their education?|$10,000|$20,000|$35,000|$60,000|1|The LLP allows for a maximum of $10,000 per year, up to a total of $20,000[cite: 15].|Ch 6: Retirement
A client's 'Earned Income' for 2025 was $80,000. Ignoring any pension adjustments, what is their RRSP contribution room for 2026?|$14,400|$18,000|$33,810|$80,000|0|RRSP room is 18% of the previous year's earned income. $80,000 * 0.18 = $14,400[cite: 16].|Ch 6: Retirement
An investor has $100,000 in a 'Joint' bank account and $100,000 in a 'TFSA' account at the same bank. If the bank fails, how much total coverage is provided by CDIC?|$100,000|$200,000|$300,000|$0|1|CDIC provides $100k coverage per member institution for each separate category (Joint and TFSA are separate)[cite: 8].|Ch 12: Regulation
Which of the following is considered 'Tax-Sheltered' growth?|Dividends in a non-registered account.|Growth and income earned within an RRSP before withdrawal.|Lottery winnings.|Rent from a property.|1|Income and growth inside registered plans (RRSP/TFSA) are shielded from immediate tax[cite: 15].|Ch 6: Retirement
A 71-year-old must mature their RRSP by December 31st. Which option allows them to keep the investments and control the annual withdrawal amount above a minimum floor?|Lump Sum Cash Withdrawal|Life Annuity|Registered Retirement Income Fund (RRIF)|TFSA Transfer|2|A RRIF allows for investment control while providing a flexible, yet mandatory, income stream[cite: 17].|Ch 6: Retirement
In a 'Defined Benefit' (DB) pension plan, who assumes the risk that the pension fund might underperform the market?|The Employee|The Employer|The Government|The Advisor|1|In a DB plan, the employer is responsible for funding any shortfall to meet the promised benefit[cite: 17].|Ch 6: Retirement
A low-income senior receives the 'Guaranteed Income Supplement' (GIS). According to Chapter 6, how is this benefit treated for tax purposes?|It is 100% taxable as income.|It is 50% taxable.|It is received tax-free.|It is treated as a capital gain.|2|Unlike OAS, the GIS is a tax-free benefit for qualifying low-income residents[cite: 18].|Ch 6: Retirement
A client is 62 and receives a CPP survivor's pension. They also qualify for their own retirement pension at 65. What is the limit on their combined payment?|There is no limit.|It is limited to the maximum retirement pension for a single person.|It is limited to 150% of the maximum.|The survivor's pension is cancelled.|1|Combined CPP benefits cannot exceed the maximum monthly retirement pension for one person[cite: 18].|Ch 6: Retirement
An investor buys a bond for $1,050 with a face value of $1,000. This bond is said to be trading at a:|Discount|Par|Premium|Maturity|2|Bonds priced above their face value ($1,000) are trading at a premium[cite: 14].|Ch 5: Investments
Which stage of the 6-step planning process involves identifying 'Gaps' between the client's current status and their goals?|Step 1|Step 2|Step 3|Step 4|2|Step 3 (Analyze and Evaluate) involves identifying shortfalls or gaps in the current plan[cite: 8].|Ch 1: Process
A client has $10,000 in a LIRA. They are 45 and want to use it for an RRSP Home Buyers' Plan (HBP) withdrawal. Is this allowed?|Yes|No|Only if they have a spouse|Only if they are first-time buyers|1|Locked-in Retirement Accounts (LIRAs) cannot be used for HBP or LLP withdrawals[cite: 17].|Ch 6: Retirement
What is the penalty for an RRSP over-contribution that exceeds the $2,000 lifetime buffer?|1% per month|5% per year|10% one-time|The government takes the excess|0|Excess contributions are subject to a 1% per month penalty tax[cite: 15].|Ch 6: Retirement
An investor has a 'Standard Deviation' of 15% and an average return of 8%. According to the normal distribution, what is the range of returns expected 68% of the time?|-7% to 23%|8% to 15%|-15% to 15%|0% to 16%|0|68% probability (1 SD) is Mean +/- SD (8% - 15% = -7% and 8% + 15% = 23%)[cite: 15].|Ch 5: Investments
A client's house is worth $400,000 and they have a $200,000 mortgage. What is their 'Loan-to-Value' (LTV) ratio?|25%|40%|50%|80%|2|LTV = Debt ($200k) / Value ($400k) = 50%[cite: 10].|Ch 3: Mortgages
Which organization manages the 'Consumer Price Index' (CPI) used to measure inflation in Canada?|Bank of Canada|CRA|Statistics Canada|OSFI|2|Statistics Canada tracks the CPI to measure the cost of living[cite: 18].|Ch 2: Economics
What is 'Asset Correlation' used for in a portfolio?|To pick the highest growth stock.|To determine how two different assets move in relation to each other.|To calculate the tax on bonds.|To determine the client's age.|1|Correlation helps reduce portfolio risk through diversification[cite: 15].|Ch 5: Investments
A client is 65 and has a net income of $120,000. If the OAS clawback threshold is $95,323, what is their repayment at a 15% rate?|$1,500.00|$3,701.55|$15,000.00|$24,677.00|1|Calculation: ($120,000 - $95,323) * 0.15 = $3,701.55[cite: 18].|Ch 6: Retirement
Which insurance 'Rider' allows the insured to buy more coverage at specific intervals without a medical exam?|Waiver of Premium|Guaranteed Insurability Option|Accidental Death|Term Conversion|1|GIO riders allow for future coverage increases regardless of health changes[cite: 12].|Ch 9: Insurance
What is 'Nominal' interest?|Interest after inflation|Stated or 'face' interest rate|Interest after tax|Interest on a car loan|1|Nominal is the interest rate before adjusting for inflation or taxes[cite: 11].|Ch 5: Math
If an investor's 'Nominal' return is 8% and inflation is 3%, what is the 'Real' rate of return?|3%|5%|8%|11%|1|Real Return = Nominal (8%) - Inflation (3%) = 5%[cite: 11].|Ch 5: Math
Which document handles 'Property' and finances while a person is alive but mentally incapable?|Last Will|Power of Attorney for Property|Power of Attorney for Personal Care|Codicil|1|A Power of Attorney for Property manages financial affairs during incapacity[cite: 22].|Ch 7: Wills
What is 'Probate'?|A life insurance term.|The legal certification that a Will is valid.|A bank charge.|A tax on the living.|1|Probate validates the Will for third parties like banks and land registries[cite: 21].|Ch 7: Wills
A client dies 'Intestate.' What determines how their assets are distributed?|The Bank|Provincial Succession Law|The Federal Government|The Executor|1|Intestacy triggers the provincial statutory formula for asset distribution[cite: 21].|Ch 7: Wills
What is 'Net Worth'?|Salary minus Tax|Assets minus Liabilities|Cash in Bank|Value of home|1|Net worth is a point-in-time snapshot of wealth (Owned minus Owed)[cite: 8].|Ch 2: Budgeting
Which 'Indicator' is the stock market?|Leading|Lagging|Coincident|Predictive|0|The stock market is a leading indicator that predicts future economic shifts[cite: 10].|Ch 2: Economics
What is 'Execution' in the context of a Will?|Reading the will.|The legal process of signing and witnessing.|Paying the final taxes.|Selling the assets.|1|Execution refers to the formal legal process of signing a Will correctly[cite: 19].|Ch 7: Wills
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Step 6 is the final ongoing stage of monitoring and review[cite: 9].|Ch 1: Process`;

const set3Raw = `Pedro and Maria Santez own a bungalow and recently took out a mortgage to buy a cottage. Pedro is the sole earner. Bryan suggests a '10-year renewable decreasing term' policy for the cottage mortgage. According to Chapter 8, what is the primary reason for this specific recommendation?|The premiums decrease as the mortgage is paid down.|The death benefit decreases over time to match the declining mortgage balance.|The policy will provide Maria with a permanent retirement income.|The policy is portable to any other lender without a new medical.|1|Decreasing term insurance is designed so the coverage matches a declining debt like a mortgage.|Ch 8: Risk Management
Johann has a son who will require lifelong financial support. Johann wants to ensure his estate is managed professionally for his son's benefit after he passes away. Which legal structure described in Chapter 7 should he establish in his Will?|A Holograph Will|A Power of Attorney for Personal Care|A Testamentary Trust|An Inter Vivos Trust|2|A Testamentary Trust is created within a Will to provide ongoing management of assets for dependents after death.|Ch 7: Wills
Vince is concerned about the financial impact of a potential job loss or a long-term disability. Bryan explains that these are examples of which category of risk?|Property Risk|Liability Risk|Personal Risk|Systematic Risk|2|Personal Risk refers to risks that directly affect an individual, such as premature death, poor health, or unemployment.|Ch 8: Risk Management
A client chooses a $1,000 deductible on their car insurance instead of a $500 deductible to lower their premium. According to Chapter 8, which risk management method are they using for the first $1,000 of loss?|Risk Avoidance|Risk Reduction|Risk Retention|Risk Transfer|2|Risk Retention (self-insurance) is the decision to personally bear the financial burden of a small loss.|Ch 8: Risk Management
A person writes their own Will entirely in their own handwriting and signs it, but there are no witnesses. In many Canadian provinces, this is a valid legal document known as a:|Formal Will|Notarial Will|Holograph Will|Codicil|2|A Holograph Will is written entirely in the testator's handwriting and signed without witnesses.|Ch 7: Wills
If a person dies 'Intestate' in Ontario in 2026 and has a spouse and children, what is the 'Preferential Share' that the spouse is entitled to before the remainder is split?|$50,000|$200,000|$350,000|$1,000,000|2|Provincial law in Ontario currently sets the spouse's preferential share at $350,000.|Ch 7: Wills
What is the primary purpose of 'Probate' (Letters Probate)?|To avoid paying the deceased's final income taxes.|To provide legal certification that a Will is valid so the executor can act.|To allow the family to bypass the 3-year attribution rule.|To appoint a Guardian for minor children while the parents are alive.|1|Probate is the legal process that certifies the validity of a Will for third parties.|Ch 7: Wills
A client wants to appoint someone to manage their bank accounts and pay their bills if they become physically unable to do so. Which document is required?|Last Will and Testament|Power of Attorney for Property|Power of Attorney for Personal Care|Living Will|1|A Power of Attorney for Property grants authority to manage financial affairs.|Ch 7: Wills
Which organization protects Canadian policyholders if their life insurance company becomes insolvent?|CDIC|CIPF|Assuris|FCAC|2|Assuris is the non-profit organization that protects policyholders in the event of an insurer's failure.|Ch 8: Risk Management
According to Assuris standards, what is the maximum protection provided for the 'Death Benefit' of a life insurance policy?|$100,000|$200,000 or 85% of the benefit (whichever is higher)|$1,000,000|$60,000 or 85% of the benefit|1|Assuris guarantees that policyholders will receive at least $200,000 or 85% of the promised death benefit.|Ch 8: Risk Management
A client wants a life insurance policy where they can increase or decrease their premiums and choose the underlying investments. Which type is most suitable?|Term-10 Insurance|Whole Life Insurance|Universal Life Insurance|Decreasing Term|2|Universal Life is an unbundled, flexible policy that allows for premium and investment choices.|Ch 8: Risk Management
What happens to a Power of Attorney for Property at the exact moment the donor dies?|It remains in effect until the funeral.|It is automatically converted into a Codicil.|It ceases to be valid immediately, and the Will takes over.|It is transferred to the Public Trustee.|2|Powers of Attorney are only for the living; at death, authority shifts to the Executor.|Ch 7: Wills
A client decides to take the bus instead of driving to avoid the risk of a car accident. According to Chapter 8, which risk management method is this?|Risk Transfer|Risk Avoidance|Risk Reduction|Risk Retention|1|Risk Avoidance involves choosing not to participate in the activity that creates the risk.|Ch 8: Risk Management
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|A Codicil|A Mandate in Case of Incapacity|A Notarial Will|A Letters Probate|1|Quebec uses a 'Mandate' for handling incapacity.|Ch 7: Wills
A client owns a cottage worth $500,000 that was purchased for $100,000. Upon death, which insurance use is most appropriate to handle the 'deemed disposition' tax?|Income Replacement|Estate Preservation|Debt Liquidation|Funeral Expenses|1|Insurance can provide the liquidity needed to pay taxes on capital assets like a cottage to preserve the estate.|Ch 8: Risk Management
If a client wants to change a small detail in their Will without rewriting the entire document, they should use a:|Holograph|Proxy|Codicil|Mandate|2|A Codicil is a legal document that amends or adds to an existing Will.|Ch 7: Wills
Which of the following is an example of 'Liability Risk'?|A house burning down.|A client being sued because a visitor tripped on their sidewalk.|A client being diagnosed with cancer.|A client losing their job.|1|Liability Risk is the risk of being held legally responsible for injury or damage to others.|Ch 8: Risk Management
A client has a $1M Life Insurance policy. Assuris guarantees they will receive at least 85% of the benefit if the insurer fails. What is the guaranteed payout?|$200,000|$850,000|$1,000,000|$150,000|1|85% of $1,000,000 is $850,000, which is higher than the $200k floor.|Ch 8: Risk Management
Who is responsible for the 'Funeral Arrangements' immediately following a death if a Will exists?|The Spouse|The Children|The Executor (Liquidator)|The Lawyer|2|The Executor has the legal authority and responsibility for funeral arrangements.|Ch 7: Wills
What is a 'Living Will' (Advance Care Directive)?|A Will for people who are still alive.|A document specifying medical treatment preferences during incapacity.|A type of trust for high-net-worth clients.|A list of assets to be sold.|1|A Living Will specifies medical preferences if one cannot speak for themselves.|Ch 7: Wills
In Ontario, if a person dies intestate with a spouse and one child, how is the estate remainder (after the preferential share) split?|100% to the spouse.|50% to the spouse and 50% to the child.|1/3 to the spouse and 2/3 to the child.|It all goes to the child.|1|Under Ontario law, if there is one child, the remainder after the preferential share is split equally (50/50).|Ch 7: Wills
Which of the following describes the 'Maturity Guarantee' of a Segregated Fund?|It guarantees the client will never lose money.|It guarantees a minimum payout (often 75% or 100%) after a specific period.|It guarantees a fixed interest rate.|It guarantees the fund will outperform the market.|1|Segregated funds offer a maturity guarantee that protects a portion of the principal over a set term.|Ch 8: Risk Management
A client is concerned about 'Reinvestment Risk.' According to Chapter 5, this risk is most prevalent in which type of investment?|Common Stocks|GICs or Bonds with fixed terms|Real Estate|Gold|1|Reinvestment risk is the danger that when a bond or GIC matures, the client will have to reinvest at a lower rate.|Ch 8: Risk Management
What is 'Per Stirpes' distribution in a Will?|Assets are split only among living children.|If a child dies before the parent, that child's share goes to their own children.|The government takes the assets.|Assets are given to charity.|1|Per Stirpes ensures that the share of a deceased beneficiary passes to their descendants.|Ch 7: Wills
Which type of life insurance policy is often described as 'Term-to-100'?|A policy that expires at age 100 with no cash value.|A policy that pays a dividend every year.|A policy with a massive cash value.|A policy that can only be bought by people over 100.|0|Term-to-100 is a permanent policy with a level premium and no cash value.|Ch 8: Risk Management
A client is 65 and has a $500,000 life insurance policy. Assuris coverage for the cash surrender value (CSV) is limited to what amount?|$100,000 or 85% of the CSV (whichever is higher)|$60,000 or 85% of the CSV (whichever is higher)|$1,000,000|$200,000|1|Assuris protects CSV up to $60,000 or 85% of the value.|Ch 8: Risk Management
What is the 'Needs Approach' to determining life insurance?|Calculating 10 times the annual salary.|Analyzing specific financial obligations like mortgages, education, and final taxes.|Buying as much as the bank allows.|Asking the spouse how much they want.|1|The Needs Approach identifies specific future financial gaps that insurance must fill.|Ch 8: Risk Management
Which 'Power of Attorney' allows for the management of property while the donor is alive and continues even if they become mentally incapable?|General Power of Attorney|Continuing or Enduring Power of Attorney|Springing Power of Attorney|Proxy|1|Continuing POAs remain valid throughout the donor's incapacity.|Ch 7: Wills
If a person dies without a Will and has no legal heirs, the estate goes to the government under what principle?|Probate|Escheat|Intestacy|Codicil|1|Escheat is the legal process where ownerless property returns to the state.|Ch 7: Wills
A client has a 'Renewable' term policy. According to Chapter 8, what does 'Renewable' mean?|The client can get a refund every year.|The policy can be renewed at the end of the term without a new medical exam.|The premiums stay the same for life.|The policy automatically turns into a TFSA.|1|Renewable term allows for continued coverage regardless of changes in health.|Ch 8: Risk Management
What is the primary role of an 'Executor' (Liquidator in Quebec)?|To choose who gets the money.|To carry out the instructions in the Will and settle the estate's debts.|To write the Will for the deceased.|To act as a judge in court.|1|The executor is responsible for asset distribution and debt settlement according to the Will.|Ch 7: Wills
Which 'Life Cycle' stage typically sees the highest need for Life Insurance?|Early Career|Accumulation (with young children and a mortgage)|Consolidation|Decumulation|1|The Accumulation phase involves high debt and high dependency, creating the greatest insurance need.|Ch 8: Risk Management
A client is diagnosed with a 'Presumptive Disability.' When does the policy typically begin to pay?|After a 90-day waiting period.|Immediately, as the waiting period is typically waived for specific catastrophic losses.|Only after they turn 65.|Only if they can no longer work any job.|1|Presumptive disabilities usually trigger immediate benefit payments for catastrophic losses like sight or speech.|Ch 8: Risk Management
What is the 'Human Life Value' approach to insurance?|Buying $1M for every child.|Calculating the present value of the individual's future earnings.|Asking the client how much they value their life.|Using a flat $500,000 for everyone.|1|Human Life Value focuses on the economic value of the earner's future income stream.|Ch 8: Risk Management
Which document is used to appoint someone to make medical decisions ONLY?|Power of Attorney for Property|Power of Attorney for Personal Care|Codicil|Mandate for Property|1|Personal Care POAs are strictly for health and lifestyle decisions.|Ch 7: Wills
A client has a 'Standard' mortgage and a 'Collateral' mortgage. Which one is generally easier to 'port' to a different lender at renewal?|Collateral|Standard|They are the same|Neither can be ported|1|Standard charge mortgages are generally easier and cheaper to transfer between institutions.|Ch 3: Mortgages
What is 'Capital Cost Allowance' (CCA)?|A tax on buildings.|Tax-deductible depreciation for a business or rental property.|The cost of buying a new car.|A type of RRSP contribution.|1|CCA allows owners to deduct the cost of depreciating assets over time.|Ch 4: Taxation
Which organization regulates the conduct of 'Investment Dealers' in Canada?|OSFI|CIRO|CDIC|Assuris|1|CIRO oversees the conduct and suitability standards for investment dealers.|Ch 12: Regulation
A client has $5,000 in 'Basic' expenses and $2,000 in 'Discretionary' expenses. If their income is $8,000, what is their 'Savings Capacity'?|$1,000|$3,000|$5,000|$8,000|0|Savings Capacity = Income ($8k) - Total Expenses ($7k) = $1,000.|Ch 2: Budgeting
What is the 'Stress Test' qualifying rate for a mortgage with a 3.5% contract rate?|3.50%|5.25%|5.50%|6.00%|2|The qualifying rate is the higher of 5.25% or the contract rate + 2% (3.5 + 2 = 5.5%).|Ch 3: Mortgages
If an investor buys a bond for $950 (Face Value $1,000), they have purchased the bond at a:|Premium|Discount|Par|Maturity|1|Bonds priced below face value are sold at a discount.|Ch 5: Investments
Which stage of the 6-step process involves 'Periodic Review'?|Step 2|Step 4|Step 5|Step 6|3|Step 6 is the ongoing monitoring and review phase.|Ch 1: Process
A client is in the 40% tax bracket and earns $1,000 in 'Eligible' dividends. With a 38% gross-up, what is their 'Taxable Income'?|$1,000|$1,380|$400|$1,400|1|Taxable income = Dividend ($1k) * 1.38 = $1,380.|Ch 4: Taxation
What is the standard 'GDS' ratio limit for most conventional mortgages?|32%|39%|42%|44%|0|The standard GDS limit is conventionally cited as 32%.|Ch 2: Lending
Which life insurance policy 'participates' in the company's profits via dividends?|Non-par Whole Life|Participating Whole Life|Term-10|Universal Life|1|Participating (Par) policies pay dividends to the policyholder.|Ch 8: Risk Management
A client is 65 and starts CPP early at age 60. By what percentage is their pension reduced?|25%|36%|42%|50%|1|Starting 60 months early reduces the pension by 0.6% per month (36% total).|Ch 6: Retirement
What is the 'Wait Period' in a disability policy?|The time you must work before buying.|The time after becoming disabled before benefits begin.|The time you must wait for a doctor's call.|The survival period for cancer.|1|The wait (elimination) period acts as a 'time deductible' before benefits start.|Ch 8: Risk Management
Which 'Indicator' is the Consumer Price Index (CPI)?|Leading|Lagging|Coincident|Predictive|2|CPI is a coincident indicator, reflecting current price levels.|Ch 2: Economics
What is a 'CRA Clearance Certificate' used for?|To buy a house.|To certify that an estate's taxes are paid before distribution.|To get a lower tax rate.|To join a professional body.|1|Executors use this to protect themselves from personal liability for the deceased's taxes.|Ch 7: Wills
Which 'Filter' in communication involves loud construction noise outside?|Psychological|Physical|Environmental|Language|2|Environmental filters are external factors that interfere with communication.|Ch 1: Process
A client has $100k in an RRSP. If they die with a spouse as beneficiary, what is the tax result?|100% taxable to the estate.|Tax-deferred rollover to the spouse's RRSP.|100% taxable to the spouse.|The bank keeps the growth.|1|RRSPs can roll over tax-deferred to a surviving spouse.|Ch 10: Estate
What is the 'Standard Deviation' of a risk-free T-Bill?|0%|10%|20%|50%|0|Risk-free assets have no price volatility, thus zero standard deviation.|Ch 5: Investments
Which insurance pays out if you are 'catastrophically' injured (loss of limbs)?|Life|Disability|Accidental Death & Dismemberment (AD&D)|Dental|2|AD&D pays specifically for catastrophic physical losses.|Ch 8: Risk Management
A client has a 'Fixed' mortgage. The 'IRD' penalty is based on what?|The 3 months interest.|The difference between the contract rate and the current market rate.|A flat $1,000.|The client's age.|1|The Interest Rate Differential measures the bank's loss in interest income.|Ch 3: Mortgages
What is the 'Asset Correlation' of -1.0?|Assets move perfectly together.|Assets move perfectly in opposite directions.|Assets have no relationship.|One is always $0.|1|Perfect negative correlation is ideal for maximum risk reduction.|Ch 5: Investments
Which stage is Step 4?|Gather|Analyze|Develop Recommendations|Implement|2|Step 4 is developing and presenting recommendations.|Ch 1: Process
A client has $10,000 in 'Interest' income. If their marginal rate is 14%, what is the federal tax?|$1,400|$5,000|$10,000|$0|0|Tax = $10,000 * 0.14 = $1,400.|Ch 4: Taxation
What is 'Net Worth'?|Salary minus Tax|Assets minus Liabilities|Cash in Bank|Value of car|1|Net worth is a point-in-time snapshot (Owned minus Owed).|Ch 2: Budgeting
Which 'Benefit' is for the spouse of a deceased CPP contributor?|OAS|GIS|Survivor's Pension|Allowance|2|CPP provides a survivor's pension to eligible spouses.|Ch 6: Retirement
What is the 'Probate Fee' in Ontario for an estate of $1M?|$0|$14,250|$15,000|$25,000|1|Calculation: ($1,000,000 - $50,000 exemption) * 1.5% = $14,250.|Ch 7: Wills
Which insurance is a 'Lump Sum' upon diagnosis of a critical illness?|Life|Disability|Critical Illness|Dental|2|Critical illness pays a lump sum if the insured survives the specified condition.|Ch 8: Risk Management
A client has a $300k mortgage and $500k house. What is the LTV?|30%|40%|60%|80%|2|LTV = Debt ($300k) / Value ($500k) = 60%.|Ch 3: Mortgages
Which 'Stage' is Step 3?|Gather|Analyze|Develop|Implement|1|Step 3 is analyzing and evaluating the data.|Ch 1: Process
Which 'Indicator' is the stock market?|Leading|Lagging|Coincident|Predictive|0|The stock market is a leading indicator of economic activity.|Ch 2: Economics
What is 'Active' Listening?|Talking more than the client.|Listening with intent to understand and providing feedback.|Taking notes only.|Thinking about your reply while they speak.|1|Active listening is a proactive communication skill.|Ch 1: Process
A client has $100k salary. Max RRSP room 2026?|$18,000|$30,000|$33,810|$100,000|2|The RRSP cap for 2026 is $33,810.|Ch 6: Retirement
Which insurance covers ANY job you are reasonably suited for?|Own Occupation|Any Occupation|Critical Illness|Term|1|Any Occupation is a stricter definition of disability.|Ch 8: Risk Management
A client earns $4,000/mo and PITH is $1,200. GDS?|25%|30%|35%|40%|1|$1,200 / $4,000 = 30%.|Ch 2: Lending
What is the 'Nominal' rate of interest?|After inflation.|Face or stated interest rate.|After tax.|The rate on a car loan.|1|Nominal is the interest rate before adjusting for inflation.|Ch 5: Math
If someone dies without a valid Will, they die?|Testate|Intestate|Probated|Escheated|1|Intestacy is dying without a valid Will.|Ch 7: Wills
What is 'Execution' of a Will?|Reading the will.|Formal process of signing and witnessing.|Paying taxes.|Distributing money.|1|Execution is the formal legal signing process.|Ch 7: Wills
A borrower is purchasing a $1.2M home. What is the min down payment?|$60,000|$120,000|$240,000|$300,000|2|Homes over $1M require a 20% down payment ($240k).|Ch 3: Mortgages
What is the 'Inclusion Rate' for capital gains in 2026?|0%|50%|75%|100%|1|Individuals include 50% of capital gains in taxable income.|Ch 4: Taxation
Which document amends an existing Will?|Power of Attorney|Codicil|Letter of Intent|Living Will|1|A Codicil is a legal amendment to an existing Will.|Ch 7: Wills
Which organization regulates bank 'solvency'?|CIRO|OSFI|CDIC|FCAC|1|OSFI ensures banks and insurers maintain adequate capital.|Ch 12: Regulation
A client has a 20% down payment on a $600k home. Is insurance mandatory?|Yes|No|Only if variable|Only for first-timers|1|Conventional mortgages (20% down) do not require CMHC insurance.|Ch 3: Mortgages
What is the 'Rule of 72' for 6% return?|6 years|8 years|12 years|15 years|2|72 / 6 = 12 years to double.|Ch 5: Math
Which stage of the cycle sees peak interest rates?|Trough|Expansion|Peak|Contraction|2|Interest rates typically peak at the top of the business cycle.|Ch 2: Economics
What is a 'LIRA'?|Locked-in Retirement Account|Insurance Risk|Interest Adjustment|Legal Agreement|0|LIRAs hold pension funds that cannot be withdrawn until retirement.|Ch 6: Retirement
Which is a 'Qualitative' data point?|Income|Debt|Retirement Goals|Net Worth|2|Goals and values are qualitative; numbers are quantitative.|Ch 1: Process
How many years of residency for full OAS?|10|20|40|50|2|40 years of residency after age 18 is required for a full OAS pension.|Ch 6: Retirement`;
