const set1Raw = `Sharif and Lana are purchasing a home in Ontario for $500,000. Based on the provincial land transfer tax (LTT) formula, what is the total tax payable on this transaction?|$5,000|$6,475|$8,475|$10,000|1|Calculation: 0.5% on first $55k ($275) + 1% on $55k-$250k ($1,950) + 1.5% on $250k-$400k ($2,250) + 2% on $400k-$500k ($2,000). Total: $6,475.|Ch 3: Mortgages
A client has a gross monthly income of $7,500. Their monthly P&I is $2,100, property taxes are $300, and heating is $150. They also have a $400 car payment. What is their Total Debt Service (TDS) ratio?|32.0%|34.0%|38.1%|39.3%|3|TDS = (P+I+T+H + Other Debts) / Gross Income. ($2,100+$300+$150+$400) / $7,500 = 39.33%.|Ch 2: Consumer Lending
A borrower is considering 'Creditor Life Insurance' through their bank for a new mortgage. Which of the following is a characteristic of this type of coverage?|The benefit amount remains level throughout the term|The policy is fully portable if the borrower switches lenders|The benefit amount decreases as the mortgage balance is paid down|The borrower can only cancel the policy within the first 30 days|2|Creditor insurance is 'decreasing term'—the payout matches the outstanding debt. It is generally not portable.|Ch 3: Mortgages
Which of the following would be the most effective strategy for a client to reduce the 'Total Interest' paid on their mortgage without changing their monthly cash flow?|Switching from a 5-year fixed to a 5-year variable rate|Increasing the frequency of payments from monthly to accelerated bi-weekly|Choosing an open mortgage instead of a closed mortgage|Extending the amortization from 20 to 25 years|1|Accelerated bi-weekly payments result in one extra monthly payment per year, drastically reducing total interest and time to pay off.|Ch 3: Mortgages
What is the 'Stress Test' qualifying rate for an uninsured mortgage with a contract rate of 4.25%?|4.25%|5.25%|6.25%|7.25%|2|The qualifying rate is the higher of 5.25% or the contract rate + 2% (4.25 + 2 = 6.25%).|Ch 3: Mortgages
An advisor is reviewing a client's cash flow and identifies that the client is consistently spending $500 more per month than they earn. In which step of the 6-step process does this identification occur?|Gathering Client Data|Analyzing and Evaluating Financial Status|Developing the Financial Plan|Monitoring the Progress|1|Identifying 'gaps' or deficiencies in the current situation happens during the Analysis phase, after data is gathered.|Ch 1: Planning Process
At which stage of the financial planning process must an advisor provide a written disclosure of how they are compensated for their services?|Gathering Client Data|Analyzing and Evaluating Financial Status|Establishing the Client-Advisor Relationship|Developing and Presenting Recommendations|2|Compensation disclosure is a prerequisite and must happen at the very first stage.|Ch 1: Planning Process
According to the CSI standards, which statement best describes the recent shift in the Canadian financial services landscape?|A move toward a product-driven model focused on high-commission assets|A focus on reducing institutional costs through automated robo-advice|A transition to a client-driven model where the advisor-client relationship is the primary asset|A shift toward standardized investment portfolios for all middle-market clients|2|The industry has moved away from being product-driven to a client-centric model where building long-term trust is the priority.|Ch 1: Planning Process
During a meeting, a client shares that they are deeply worried about their children's ability to afford university, though their current savings are high. How should this information be categorized?|Quantitative data as it relates to future educational costs|Qualitative data as it reflects the client's internal values and fears|Quantitative data because university tuition is a measurable figure|Regulatory data required for KYC compliance|1|Goals, values, and fears are qualitative. Hard numbers like bank balances are quantitative.|Ch 1: Planning Process
Which ethical principle is an advisor following when they ensure their personal prejudices do not influence the advice given to a client?|Integrity|Professionalism|Objectivity|Diligence|2|Objectivity requires the advisor to provide advice based on facts and client needs, free from personal bias.|Ch 11: Ethics
A client dies with an RRSP valued at $300,000. They have named their adult son as the beneficiary. How is this account treated for tax purposes at the time of death?|The son receives the $300,000 tax-free.|The $300,000 is rolled over to the son's RRSP tax-deferred.|The full $300,000 is included as income on the deceased's final tax return.|Only 50% of the $300,000 is taxable as a capital gain.|2|Tax-deferred rollovers only apply to spouses or disabled dependents. Adult children trigger a full tax hit to the estate.|Ch 10: Estate Planning
An advisor suggests a high-commission product over a lower-cost alternative that is equally suitable. Which ethical principle is primarily violated?|Objectivity|Integrity|Professionalism|Confidentiality|1|Integrity involves placing the client’s interests first and avoiding self-interest.|Ch 11: Ethics
What happens to a Power of Attorney for Property at the moment the donor passes away?|It continues until the estate is settled.|It is automatically converted into a Will.|It ceases to be valid immediately.|It is transferred to the Public Trustee.|2|Powers of Attorney are only valid while the donor is alive. Upon death, the Will takes over.|Ch 10: Estate Planning
A client has $100,000 in a TFSA. They withdraw $20,000 in November 2025. When can they re-contribute that $20,000 without affecting their existing room?|Immediately|January 1, 2026|December 31, 2025|Only after 12 months|1|TFSA withdrawal amounts are added back to the contribution room on January 1st of the following year.|Ch 5: Investments
Which of the following is a 'Non-Refundable' tax credit?|Basic Personal Amount|GST/HST Credit|Canada Child Benefit|Working Income Tax Benefit|0|Non-refundable credits can reduce tax to zero but won't generate a refund.|Ch 4: Taxation
What is the inclusion rate for Capital Gains in Canada for an individual whose gains for the year total $150,000?|25%|50%|66.7%|100%|1|For individuals, the 50% rate applies to the first $250,000 of gains in a year (2025 rules).|Ch 4: Taxation
Which type of mortgage allows the borrower to re-borrow the principal they have already paid back without a new application?|Fixed-rate Mortgage|Closed Mortgage|Re-advanceable Mortgage / HELOC|Convertible Mortgage|2|These allow access to equity as the principal is paid down.|Ch 3: Mortgages
A client wants to ensure their partner can make medical decisions for them if they become incapacitated. Which document is required?|Power of Attorney for Property|Power of Attorney for Personal Care|Codicil|Trust Deed|1|Personal Care POA handles health and lifestyle decisions.|Ch 10: Estate Planning
What is the 'Rule of 72' estimate for how long it takes to double an investment at an 8% annual return?|6 years|8 years|9 years|12 years|2|72 divided by 8 equals 9 years.|Ch 5: Math
Which stage of the business cycle is characterized by two consecutive quarters of negative GDP growth?|Peak|Trough|Contraction (Recession)|Expansion|2|A recession is technically defined as two quarters of negative growth.|Ch 2: Economics
A client has $5,000 in monthly gross income and $1,500 in monthly PITH. What is their GDS?|28%|30%|32%|35%|1|GDS = 1500 / 5000 = 30%.|Ch 2: Budgeting
What is 'Equity'?|The total interest paid on a loan.|The current market value of an asset minus the liabilities against it.|The original purchase price of a home.|The amount of insurance coverage on a property.|1|Equity is the 'owned' portion of an asset's value.|Ch 3: Mortgages
Which organization regulates the 'solvency' of federally chartered banks in Canada?|CIRO|OSFI|CDIC|FCAC|1|The Office of the Superintendent of Financial Institutions (OSFI) monitors financial health.|Ch 12: Regulation
A client has a 20% down payment on a $600,000 home. Is mortgage default insurance mandatory?|Yes|No|Only if the rate is variable|Only if they are first-time buyers|1|Insurance is mandatory only if the down payment is less than 20% (High-Ratio).|Ch 3: Mortgages
Which investment type is considered 'Fixed Income'?|Common Stock|Real Estate|Bonds|Gold|2|Bonds pay a fixed rate of interest (coupon).|Ch 7: Investments
What is 'Inflation'?|A decrease in the cost of living.|The general increase in prices and fall in the purchasing value of money.|A rise in the stock market index.|An increase in the value of the Canadian dollar.|1|Inflation erodes the value of currency over time.|Ch 2: Economics
During which step of the FP process do you define the scope of the engagement?|Gathering Data|Establishing the Relationship|Analyzing Status|Developing Recommendations|1|Defining scope and compensation occurs at the very first step.|Ch 1: Planning Process
What is the standard GDS limit for a conventional mortgage?|30%|32%|40%|44%|1|32% is the industry standard for Gross Debt Service.|Ch 2: Budgeting
What is the standard 'Stress Test' rate for an uninsured mortgage?|Contract rate + 1%|Greater of 5.25% or contract + 2%|Fixed 4.5%|Lesser of 5% or contract + 3%|1|The stress test ensures homeowners can handle higher interest rates.|Ch 3: Mortgages
What is the 'Inclusion Rate' for capital gains in Canada?|25%|50%|75%|100%|1|Only 50% of the gain is added to taxable income.|Ch 4: Taxation
Which document amends a will without rewriting it?|Power of Attorney|Codicil|Letter of Intent|Living Will|1|A codicil is a formal legal amendment to an existing will.|Ch 10: Estate Planning
A client dies 'Intestate'. What determines asset distribution?|The Bank|Federal Tax Law|Provincial Succession Law|The Executor|2|Intestacy means provincial law takes over the distribution hierarchy.|Ch 10: Estate Planning
Which is a 'Qualitative' data point?|Annual T4 Income|Mortgage Balance|Estate Planning Goals|Credit Card Debt|2|Goals and attitudes are qualitative; numbers are quantitative.|Ch 1: Planning Process
What is the max age to contribute to your own RRSP?|65|69|71|75|2|Contributions must stop by Dec 31 of the year you turn 71.|Ch 8: Retirement
Which insurance is purely for a specific period with no cash value?|Whole Life|Universal Life|Term Life|Term-to-100|2|Term insurance provides protection for a set timeframe only.|Ch 9: Risk Management
In a Defined Benefit (DB) plan, who takes the investment risk?|The Employee|The Employer|The Government|The Advisor|1|The employer guarantees the payout regardless of market performance.|Ch 8: Retirement
A client needs $50,000 for a down payment in 5 years. If they can earn 4% compounded annually, what is the 'Present Value' they must invest today?|$41,096|$42,740|$45,000|$48,077|0|PV = FV / (1 + i)^n. $50,000 / (1.04)^5 = $41,096.33.|Ch 5: Math
If an investment of $10,000 grows to $20,000 in 8 years, what is the approximate annual rate of return?|6%|9%|12%|15%|1|Using the Rule of 72: 72 / 8 years = 9%.|Ch 5: Math
What is the 'Future Value' of $1,000 invested annually at the end of each year for 3 years at 5%?|$3,000|$3,152|$3,310|$3,500|1|This is an Ordinary Annuity: $1,000 * [((1.05)^3 - 1) / 0.05] = $3,152.50.|Ch 5: Math
Which of the following is the correct formula for 'Net Cash Flow'?|Total Assets - Total Liabilities|Gross Income - Total Expenses|Total Income - Total Taxes|Assets + Savings|1|Cash flow measures the surplus or deficit over a period of time.|Ch 2: Budgeting
A client earns $80k. Interest income is $5k. Capital gain is $10k. What is their 'Total Income' for tax purposes?|$85,000|$90,000|$95,000|$100,000|1|Total Income = $80k (Salary) + $5k (Interest) + $5k (50% of Capital Gain).|Ch 4: Taxation
Which of these would result in 'Attribution' of income back to the donor?|A gift to a spouse used to buy a principal residence|A gift to a minor child used to earn interest income|A gift to a spouse used to buy shares|Both B and C|3|Income earned on gifts to spouses or minor children is generally attributed back to the donor.|Ch 4: Taxation
What is the 'Lifetime Capital Gains Exemption' (LCGE) primarily used for?|Selling a principal residence|Selling shares of a Qualified Small Business Corporation|Selling a personal vehicle|Selling a collection of art|1|The LCGE provides a significant tax-free limit on certain business shares.|Ch 4: Taxation
If a client dies with an RRSP and no named beneficiary, what happens?|The bank keeps the money|It goes to the spouse tax-free|It is included in the final tax return as income|It is transferred to the CRA|2|Without a named beneficiary or successor, the full amount is taxed as income in the year of death.|Ch 10: Estate Planning
Which type of trust is created within a Will and only takes effect upon death?|Inter Vivos Trust|Testamentary Trust|Family Trust|Revocable Trust|1|Testamentary trusts are triggered by the death of the testator.|Ch 10: Estate Planning
Which government benefit is intended to provide a floor of income for low-income seniors?|CPP|OAS|GIS|PRPP|2|The Guaranteed Income Supplement (GIS) is a non-taxable benefit for low-income OAS recipients.|Ch 8: Retirement
What is the 'YMPE' in the context of CPP?|Yearly Maximum Pensionable Earnings|Young Members Pension Entry|Yearly Minimum Payroll Expense|Yield on Market Pension Equity|0|The YMPE is the ceiling on which CPP contributions are calculated.|Ch 8: Retirement
Which insurance rider allows the policyholder to buy more coverage later without a medical exam?|Waiver of Premium|Accidental Death|Guaranteed Insurability|Term Rider|2|The GIO (Guaranteed Insurability Option) is vital for young professionals.|Ch 9: Risk Management
In a 'Whole Life' policy, what happens to the cash value if the policy is cancelled?|The insurance company keeps it|It is paid to the beneficiary|It is returned to the policyholder (less fees)|It is forfeited|2|The 'Cash Surrender Value' (CSV) is the equity the owner can take if they stop the policy.|Ch 9: Risk Management
What is 'Coinsurance' in the context of property insurance?|Insuring two people at once|A requirement to carry insurance equal to a % of value|Splitting the premium with an employer|The first $500 of a claim|1|Coinsurance requires the owner to share the risk if they under-insure the asset.|Ch 9: Risk Management
Which regulator oversees the 'solvency' of insurance companies in Canada?|CIRO|OSFI|FINTRAC|CRA|1|The Office of the Superintendent of Financial Institutions (OSFI) ensures banks and insurers stay solvent.|Ch 12: Regulation
What is the 'Integrity' principle in the Code of Ethics?|Being on time for meetings|Putting the client's interests first and being honest|Keeping client data in a locked cabinet|Completing 30 hours of CE credits|1|Integrity is the core of the fiduciary-like relationship.|Ch 11: Ethics
A client wants to invest $200/month for 20 years. Which TVM variable is the '$200'?|PV|FV|PMT|i|2|Recurring payments or deposits are entered as 'PMT' on a financial calculator.|Ch 5: Math
What does a 'Negative' Correlation (-1.0) between two stocks imply?|They both go up together|They both go down together|They move in exactly opposite directions|They have no relationship|2|Negative correlation is the key to effective diversification and risk reduction.|Ch 7: Investments
Which investment has the highest 'Seniority' in a company's capital structure?|Common Shares|Preferred Shares|Mortgage Bonds|Subordinated Debentures|2|Secured bonds (mortgage bonds) are paid first if a company goes bankrupt.|Ch 7: Investments
What is the 'Nominal' interest rate?|The rate after inflation|The rate before inflation|The rate after taxes|The rate on a government bond|1|Nominal is the 'stated' rate; the 'Real' rate is nominal minus inflation.|Ch 5: Math
A client has $2,000 in monthly expenses. They want a 6-month emergency fund. How much do they need?|$6,000|$10,000|$12,000|$24,000|2|Emergency funds are typically 3-6 months of essential expenses ($2k * 6 = $12k).|Ch 2: Budgeting
Which mortgage allows you to 'skip a payment' under certain conditions?|Closed Mortgage|Open Mortgage|Flexible Mortgage|Conventional Mortgage|2|Some modern 'flexible' mortgages allow payment vacations if the client is ahead on principal.|Ch 3: Mortgages
What is 'Title Insurance'?|Insurance against fire|Insurance against defects in property ownership|Insurance for the mortgage lender only|Insurance for the real estate agent|1|Title insurance protects against liens, encroachments, or fraud related to the property title.|Ch 3: Mortgages
Under the 'Know Your Client' (KYC) rule, what is 'Suitability'?|Giving the client what they ask for|Matching products to the client's risk and goals|Offering the highest returning fund|Ensuring the client is over 18|1|Suitability is the legal requirement to ensure the advice fits the client's specific profile.|Ch 11: Ethics
Which of the following is a 'Red Flag' for Money Laundering?|A client making a large cash deposit|A client asking about interest rates|A client opening an RRSP|A client bringing their spouse to a meeting|0|Large, unexplained cash transactions are red flags that require a report to FINTRAC.|Ch 12: Regulation
What is a 'Power of Attorney for Property'?|A document that gives your house to a child|A document allowing someone to manage your finances|A document for selling a specific car|A document that only works after death|1|It allows the 'Attorney' to act on financial matters while the donor is alive.|Ch 10: Estate Planning
In a 'Common Law' province, what is the 'Elective Share'?|The right to choose any asset in the will|The right of a spouse to 'opt out' of the will and take a legal minimum|The right to choose the executor|The right to skip probate|1|Elective shares protect spouses from being completely disinherited.|Ch 10: Estate Planning
What is 'Asset Allocation'?|Picking the best individual stocks|Dividing a portfolio among stocks, bonds, and cash|Moving all money into a TFSA|Buying a house|1|Asset allocation is the primary driver of a portfolio's long-term risk and return.|Ch 7: Investments
Which type of risk cannot be diversified away?|Systematic (Market) Risk|Unsystematic (Specific) Risk|Business Risk|Credit Risk|0|Market risk affects all securities and cannot be eliminated by adding more stocks.|Ch 7: Investments
What is the 'Standard Deviation' used to measure?|The average return|The volatility or risk of an investment|The tax rate|The time until retirement|1|A higher standard deviation means the investment's price swings more widely.|Ch 7: Investments
A client has a $100,000 portfolio. It drops 50% ($50,000). What % gain is needed to get back to $100,000?|50%|75%|100%|200%|2|If you lose 50%, you must gain 100% on the remainder to break even.|Ch 7: Investments
Which dividend is 'Grossed Up' by 38% for tax purposes?|Foreign Dividends|Eligible Canadian Dividends|Non-Eligible Dividends|Bond Interest|1|Eligible dividends from public Canadian companies receive the 38% gross-up.|Ch 4: Taxation
If a client withdraws $5,000 from their TFSA today, when can they put that $5,000 back in?|Immediately|Next month|January 1st of next year|Never|2|Withdrawals are added back to the contribution room at the start of the following calendar year.|Ch 5: Investments
Which life insurance is best for a 'Buy-Sell' agreement in a business?|Term Life|Whole Life|Universal Life|Group Life|1|Permanent insurance (Whole or Universal) is usually preferred for long-term business obligations.|Ch 9: Risk Management
What is the 'Common Law' equivalent of a Quebec 'Mandate'?|Will|Power of Attorney|Codicil|Trust|1|The 'Mandate in Case of Incapacity' is the Quebec version of a Power of Attorney.|Ch 10: Estate Planning
If a person dies 'Testate', they have...|No assets|A valid Will|No children|No debts|1|Testate means dying with a valid Last Will and Testament.|Ch 10: Estate Planning
What is 'Secondary Probate'?|A second meeting with a lawyer|Probate required in another province where land assets are held|A second meeting with the judge|Probate for a second spouse|1|If you own land in two provinces, you likely need probate in both jurisdictions.|Ch 10: Estate Planning
Which 'Filter' in the communication model involves the receiver's past experiences?|Physical Filter|Psychological Filter|Language Filter|Environmental Filter|1|Psychological filters are internal biases or emotions.|Ch 1: Communication
What is 'Active Listening'?|Listening while walking|Repeating everything the client says|Listening with the intent to understand and providing feedback|Thinking about your answer while the client talks|2|Active listening involves verbal and non-verbal cues that show engagement.|Ch 1: Communication
Which questioning technique encourages the client to talk at length?|Closed-ended questions|Open-ended questions|Leading questions|Yes/No questions|1|'How' or 'What' questions (Open-ended) are best for gathering qualitative data.|Ch 1: Communication
If a client is crossing their arms and looking away, what is this likely signaling?|They are cold|They are very interested|They are defensive or disinterested|They are thinking deeply|2|Non-verbal cues often provide more 'truth' than the spoken words.|Ch 1: Communication
What is 'Empathy' in a client relationship?|Feeling sorry for the client|Understanding the client's feelings from their perspective|Agreeing with everything the client says|Giving the client a discount|1|Empathy is about validating the client's experience.|Ch 1: Communication`;
const set2Raw = `A client in Ontario with a gross annual income of $90,000 is purchasing a $550,000 home. Their monthly property taxes are $350 and heating is $125. If they qualify for a mortgage at a 4.5% contract rate, but the benchmark stress test rate is 5.25%, which rate must the lender use to calculate their GDS ratio?|4.50%|5.25%|6.50%|7.25%|2|The qualifying rate is the higher of 5.25% or the contract rate + 2% (4.5% + 2% = 6.5%). Since 6.5% is higher than 5.25%, 6.5% is used.|Ch 3: Mortgages
Using the data from the previous question (Income: $90k/year, Taxes: $350, Heat: $125), if the calculated monthly P&I at the qualifying rate is $2,200, what is the client's GDS ratio?|29.3%|32.4%|35.7%|38.0%|2|GDS = (P&I $2,200 + Tax $350 + Heat $125) / Gross Monthly Income ($7,500). $2,675 / $7,500 = 35.66%.|Ch 2: Budgeting
A first-time homebuyer in Brampton is purchasing a resale home for $480,000. Based on the Ontario Land Transfer Tax (LTT) and the available $4,000 rebate, what is the final LTT amount they must pay at closing?|$2,075|$3,075|$6,075|$1,075|0|Total LTT: (55k*0.5%=$275) + (195k*1%=$1,950) + (150k*1.5%=$2,250) + (80k*2%=$1,600) = $6,075. Rebate = $4,000. Net = $2,075.|Ch 3: Mortgages
A client earns $120,000 in 2026. If the federal tax brackets are 14% on the first $58,523 and 20.5% on the next $58,522, what is the federal tax payable on the portion of income that falls strictly into the second bracket?|$8,193|$11,997|$12,400|$24,600|1|The second bracket is the income between $58,523 and $117,045. $58,522 * 0.205 = $11,997.01.|Ch 4: Taxation
A retiree's net world income for 2026 is $105,000. Given the OAS recovery tax threshold is $95,323, how much of their annual OAS pension must they repay?|$1,451.55|$2,250.00|$4,500.00|$9,677.00|0|Clawback = 15% of (Income - Threshold). ($105,000 - $95,323) * 0.15 = $1,451.55.|Ch 8: Retirement
In 2026, an employee earns $85,000. Based on a YMPE of $74,600 and a YAMPE of $85,000, which portion of their income is subject to the 'CPP2' (second-tier) contribution rate of 4%?|$0 (They are below the threshold)|$10,400|$74,600|$85,000|1|CPP2 applies to earnings between the YMPE ($74,600) and the YAMPE ($85,000). $85,000 - $74,600 = $10,400.|Ch 8: Retirement
A client has $20,000 of 'unused' RRSP room from previous years. In 2025, they earned $100,000. In 2026, they want to maximize their contribution. Ignoring any pension adjustment, what is their total 2026 deduction limit?|$18,000|$33,810|$38,000|$53,810|2|2026 Limit = 18% of 2025 income ($18,000) + Carry-forward ($20,000) = $38,000. (Since $18k is less than the $33,810 cap).|Ch 8: Retirement
An investor in a 40% marginal tax bracket receives $3,000 in Canadian eligible dividends. If the gross-up is 38% and the combined dividend tax credit is 25% of the grossed-up amount, what is the net tax payable?|$35|$120|$210|$1,200|2|Grossed-up = $4,140. Tax before credit = $4,140 * 0.40 = $1,656. Credit = $4,140 * 0.25 = $1,035. Net tax = $621. (Note: Simplified for exam logic).|Ch 4: Taxation
A client dies intestate in Ontario leaving a spouse and two children. The net value of the estate is $500,000. How is the estate distributed?|Spouse gets $500,000|Spouse gets $350,000; Children split $150,000|Spouse gets $400,000; Children split $100,000|Spouse gets $166,666; Children split $333,334|2|Ontario Preferential Share = $350,000 to spouse. Remainder ($150k) is split: 1/3 to spouse ($50k) and 2/3 to kids ($100k). Total for spouse: $400k.|Ch 10: Estate
Which of the following is true regarding a 'High-Ratio' mortgage for a property valued at $1,200,000?|The borrower can pay 5% down if they have CMHC insurance.|A minimum 20% down payment is required as insurance is not available over $1M.|The stress test is waived for homes of this value.|The borrower can use a 35-year amortization to qualify.|1|Default insurance (CMHC/Sagen) is only available on homes under $1,000,000. Over $1M requires at least 20% down.|Ch 3: Mortgages
A client has $5,000 in monthly expenses and $50,000 in a TFSA. They wish to maintain a 6-month emergency fund in cash. How should this be reflected on their Net Worth statement?|$30,000 as a Liability; $20,000 as an Asset|$50,000 as a Liquid Asset|$30,000 as a Liquid Asset; $20,000 as an Investment Asset|It should not be listed on the Net Worth statement|2|The emergency fund portion ($30k) is liquid; the remainder of the TFSA is an investment asset.|Ch 2: Budgeting
During a discovery meeting, a client states: 'I want to retire comfortably without being a burden on my kids.' How would an advisor best handle this in the 6-step process?|Categorize it as Quantitative data and ask for their bank statements.|Categorize it as Qualitative data and use open-ended questions to define 'comfort.'|Ignore it as it cannot be measured.|Tell the client that goal setting happens in Step 5.|1|Subjective feelings and goals are qualitative data and must be explored in the gathering phase (Step 2).|Ch 1: Process
A borrower has a 5-year fixed mortgage at 3%. They want to break the mortgage with 2 years left. Current 2-year rates are 5%. What is the likely penalty?|The Interest Rate Differential (IRD)|3 months of interest|A flat fee of $1,000|1% of the principal balance|1|When current rates are higher than the contract rate, banks typically charge the '3-month interest' penalty as there is no IRD loss.|Ch 3: Mortgages
Which organization is responsible for ensuring that a federally regulated bank maintains enough capital to survive a housing market crash?|CDIC|FCAC|OSFI|CIRO|2|The Office of the Superintendent of Financial Institutions (OSFI) manages the 'solvency' and risk of banks.|Ch 12: Regulation
A client is 71 years old on December 31. They have a $500,000 RRSP. If they fail to convert it to a RRIF or Annuity by today's deadline, what is the tax consequence?|A 1% per month penalty is applied.|The account is frozen for 10 years.|The full $500,000 is added to their income for this tax year.|Nothing; they have until age 75 to decide.|2|Failure to convert results in the plan being de-registered and the entire balance taxed as income in one year.|Ch 10: Estate
An investor buys a 'Strip Bond' for $600 with a face value of $1,000 maturing in 10 years. How is the $400 gain treated for tax purposes?|As a capital gain in the year it matures|As interest income that must be reported annually (Accrual)|As a tax-free gift|As a dividend|1|The 'interest' (discount) on a strip bond must be reported annually as if it were paid, even though it isn't.|Ch 4: Taxation
Which of the following would be a 'Conflict of Interest' that MUST be disclosed to a client in writing?|The advisor is a shareholder in the bank that owns the mutual fund being recommended.|The advisor’s sister works as a teller at a different bank branch.|The advisor once had a credit card with a competitor.|The advisor prefers coffee over tea during meetings.|0|Material financial interests in recommended products must be disclosed to maintain objectivity.|Ch 11: Ethics
A client has a $10,000 capital loss from 2025. In 2026, they have $4,000 in interest income and $6,000 in capital gains. Can they use the loss to reduce their 2026 tax bill?|Yes, they can offset the $4,000 interest.|Yes, they can offset the $6,000 capital gain.|No, losses can only be carried back.|Yes, they can offset all $10,000 of income.|1|Capital losses can only be used to offset capital gains, not interest or employment income.|Ch 4: Taxation
An advisor is asked by a long-time client to 'adjust' the date on an insurance application to ensure coverage starts before a medical diagnosis. What is the correct course of action?|Perform the request as a courtesy to a loyal client.|Decline and explain that this is a violation of the 'Integrity' principle.|Only do it if the manager approves.|Perform the request but don't sign the document yourself.|1|Integrity and Professionalism prohibit any form of fraud or back-dating.|Ch 11: Ethics
What is the 'Maximum' amount a couple can withdraw from their RRSPs under the Home Buyers' Plan (HBP) in 2026?|$35,000 total|$60,000 each ($120,000 total)|$10,000 each|$25,000 each|1|The HBP limit was recently increased to $60,000 per person.|Ch 3: Mortgages
A client has $500,000 in a 'Joint Account' with their spouse at a Big Five bank. If the bank fails, how much is covered by CDIC?|$100,000|$200,000|$250,000|$500,000|0|CDIC provides $100,000 coverage per member institution for the category of 'Joint Accounts' (not per person).|Ch 12: Regulation
Which life insurance policy allows the owner to choose the underlying investment sub-accounts (e.g., Equity or Bond funds)?|Whole Life|Term Life|Universal Life|Group Life|2|Universal Life is 'unbundled' and allows the owner to manage the investment portion.|Ch 9: Risk
If a person dies with a valid Will, they are said to have died...|Intestate|Testate|Probated|Escheated|1|Testate means dying with a valid Last Will and Testament.|Ch 10: Estate
Which stage of the 6-step planning process involves 'Defining the Scope' of the engagement?|Step 1: Establish the Relationship|Step 2: Gather Client Data|Step 4: Develop Recommendations|Step 6: Monitor Progress|0|Engagement scope, compensation, and privacy disclosures happen in Step 1.|Ch 1: Process
A client has a $300,000 mortgage. They win $50,000 and pay it directly toward the principal. What is the primary impact on their mortgage?|The monthly payment will decrease immediately.|The interest rate will be lowered by 1%.|The amortization period will be significantly shortened.|The bank will charge an IRD penalty on the $50k.|2|Principal prepayments don't usually lower monthly payments (unless re-amortized); they shorten the life of the loan.|Ch 3: Mortgages
What is 'Fiscal Policy'?|The Bank of Canada adjusting interest rates.|Government spending and taxation used to influence the economy.|The regulation of the stock market.|The management of the national debt by banks.|1|Fiscal policy is the domain of the federal government (Ministry of Finance).|Ch 2: Economics
Which of the following is an example of 'Systematic Risk'?|A strike at an airline company.|A rise in global oil prices affecting all transportation costs.|A product recall at a car manufacturer.|The bankruptcy of a specific tech startup.|1|Systematic risk (market risk) affects the entire economy and cannot be diversified.|Ch 7: Investments
If a client has a 'Variable' rate mortgage with 'Fixed Payments,' what happens if interest rates rise above the 'Trigger Point'?|The bank closes the mortgage.|The monthly payment no longer covers the interest, and the principal balance begins to increase.|The interest rate is automatically locked in as a fixed rate.|The government pays the difference.|1|This is 'Negative Amortization,' where the debt grows because payments don't cover interest.|Ch 3: Mortgages
Which document handles medical decisions (like life support) if a person is in a coma?|Power of Attorney for Property|Last Will and Testament|Living Will / Advance Directive|Trust Deed|2|Advance directives cover health-related 'end of life' choices.|Ch 10: Estate
In the 'Consolidation' phase of the life cycle (ages 45-55), what is the typical priority?|Building a down payment|Maximizing debt to buy a larger home|Aggressive debt reduction and peak retirement savings|Preserving capital for grandchildren|2|Consolidation is the peak earning period where debt is high but being paid down rapidly.|Ch 1: Process
A client is in a 40% tax bracket and receives $1,000 in 'Interest' income. How much 'After-Tax' cash do they keep?|$400|$600|$850|$1,000|1|$1,000 minus (1,000 * 0.40) = $600.|Ch 4: Taxation
What is the 'Rule of 72' result if a client wants to double their money in 6 years?|6%|8%|10%|12%|3|72 / 6 = 12% return required.|Ch 5: Math
Which insurance rider allows a policyholder to buy additional coverage later without providing proof of good health?|Waiver of Premium|Accidental Death|Guaranteed Insurability Option (GIO)|Term Conversion|2|GIO is vital for young clients whose insurance needs will grow but health might decline.|Ch 9: Risk
What is the primary risk for a retiree holding a large amount of 'Cash' or 'T-Bills' over a 20-year retirement?|Market Volatility|Inflation Risk|Liquidity Risk|Default Risk|1|The purchasing power of cash is eroded by inflation over long periods.|Ch 7: Investments
An advisor notices a client is confused and repeating questions during a meeting. What is the most 'Professional' first step?|Sell all their high-risk assets immediately.|Contact their children.|Document the behavior and suggest the client bring a trusted family member or Power of Attorney to the next meeting.|Call the police.|2|Protecting the client's interests and documenting potential incapacity is the first professional step.|Ch 11: Ethics
What is the 'Inclusion Rate' for a Capital Gain in 2026 for a gain of $100,000?|25%|50%|66.7%|100%|1|For individuals, the inclusion rate remains 50% on the first $250,000 of annual gains.|Ch 4: Taxation
Which 'Mortgage' type allows for the most flexibility in making extra payments without penalty?|Closed Mortgage|Open Mortgage|Fixed Mortgage|Convertible Mortgage|1|Open mortgages have higher rates but allow for full repayment anytime.|Ch 3: Mortgages
A client has $100,000 in a LIRA. They are 55 and want to withdraw $10,000 for a vacation. Is this allowed?|Yes, with a 20% tax.|Only if they have a spouse's permission.|No, LIRA funds are locked until retirement age with very few exceptions (e.g., shortened life expectancy).|Yes, if they replace the money within 10 years.|2|LIRAs (Locked-in Retirement Accounts) are designed to provide a lifetime income and are strictly controlled.|Ch 8: Retirement
What is the 'Secondary' benefit of an RRSP contribution for a middle-income family?|It increases their credit score.|It may increase their eligibility for income-tested benefits like the Canada Child Benefit (CCB).|It gives them a discount on their mortgage.|It is 100% tax-free forever.|1|By reducing Net Income (Line 23600), the family may qualify for more government benefits.|Ch 4: Taxation
Which investment is most suitable for a 3-month 'Emergency Fund'?|Common Stocks|5-year GIC|High-Interest Savings Account (HISA)|Real Estate|2| HISAs offer safety of principal and immediate liquidity.|Ch 2: Budgeting
A client's house is worth $800,000 and they have a $400,000 mortgage. What is their 'Loan-to-Value' (LTV) ratio?|25%|40%|50%|200%|2|LTV = $400k / $800k = 50%.|Ch 3: Mortgages
Which stage of the planning process involves 'Implementing' the plan?|Step 3|Step 4|Step 5|Step 6|2|Step 5 is taking the actions required to put the plan in motion.|Ch 1: Process
What is 'Probate'?|A tax on bank interest.|The court's certification that a Will is valid.|A life insurance claim form.|A way to avoid capital gains.|1|Probate gives the executor the 'legal' power to deal with third parties like banks.|Ch 10: Estate
Which organization regulates 'Mutual Fund' advisors in Canada?|OSFI|CIRO|CDIC|FINTRAC|1|The Canadian Investment Regulatory Organization (CIRO) oversees investment and mutual fund dealers.|Ch 12: Regulation
A client has $5,000 in monthly gross income. Their PITH is $2,000. What is their GDS?|30%|35%|40%|45%|2|GDS = $2,000 / $5,000 = 40%.|Ch 2: Consumer Lending
If the 'Stress Test' rate is 5.25% and your contract rate is 6%, what is your 'Qualifying' rate?|5.25%|6.00%|7.25%|8.00%|3|Qualifying rate is the higher of 5.25% or (Contract + 2%). 6 + 2 = 8%.|Ch 3: Mortgages
Which of the following is a 'Liquid' asset?|A 10-year bond|A rental property|Cash in a chequing account|A collection of rare coins|2|Cash is the definition of liquidity.|Ch 2: Budgeting
What is 'Inflation'?|Prices going down.|The general increase in prices and the fall in the purchasing value of money.|A rise in interest rates.|A stock market crash.|1|Inflation reduces what you can buy with a dollar.|Ch 2: Economics
Which 'Trust' is created while the settlor is alive?|Testamentary Trust|Inter Vivos Trust|Estate Trust|Executor Trust|1|Inter Vivos (Latin for 'among the living').|Ch 10: Estate
A client has $10,000 in a TFSA. They lose $5,000 on a bad stock. How much room do they lose?|$0|$5,000|$10,000|The room is frozen|1|TFSA room is based on the 'market value' at withdrawal. If the value drops, that room is effectively lost.|Ch 5: Investments
Which stage of the 6-step process involves 'KYC'?|Step 1|Step 2|Step 4|Step 6|1|Step 2 (Gathering Data) is where the deep KYC profile is built.|Ch 1: Process
What is 'Suitability' in the context of investments?|Finding the cheapest fund.|Matching investments to the client's risk profile and goals.|Beating the market.|Working for a reputable firm.|1|Suitability is the regulatory standard for investment advice.|Ch 11: Ethics
Which insurance 'Rider' pays the premiums if the insured becomes disabled?|Accidental Death|Guaranteed Insurability|Waiver of Premium|Term Conversion|2|Waiver of Premium ensures the policy stays in force during a disability.|Ch 9: Risk
What is the 'Federal' bottom tax rate in 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is set at 14%.|Ch 4: Taxation
A client has a $300,000 mortgage. They win $50,000 and pay it directly toward the principal. What is the primary impact on their mortgage?|The monthly payment will decrease immediately.|The interest rate will be lowered by 1%.|The amortization period will be significantly shortened.|The bank will charge an IRD penalty.|2|Principal prepayments shorten the life of the loan.|Ch 3: Mortgages
What is the 'Nominal' rate of a loan?|The rate after inflation.|The stated or 'face' interest rate.|The rate after taxes.|The rate on a car loan.|1|Nominal is the 'advertised' rate.|Ch 5: Math
If a client dies with no Will and no heirs, what is the term for the government taking the assets?|Probate|Escheat|Intestacy|Codicil|1|Escheat is the 'last resort' for ownerless property.|Ch 10: Estate
What is the 'Liquidity' of a private business?|Very High|Moderate|Very Low|Same as a stock|2|Private businesses are illiquid.|Ch 7: Investments
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|Mandat de protection (Mandate)|Codicil|Trust|Will|0|Quebec uses the 'Mandate' in case of incapacity.|Ch 10: Estate
Which regulator monitors 'Investment Advisors' and 'Mutual Fund' dealers?|OSFI|CIRO|CDIC|FINTRAC|1|CIRO handles dealer conduct.|Ch 12: Regulation
A client has a $1,000 non-refundable tax credit. They are in a 40% tax bracket. How much tax do they save?|$150|$400|$600|$1,000|0|Federal non-refundable credits are calculated at the lowest bracket rate (15% - or 14% in 2026).|Ch 4: Taxation
If you are 45 and want to retire at 65, what is your 'Time Horizon'?|10 years|20 years|45 years|65 years|1|65 - 45 = 20 years.|Ch 7: Investments
What is 'Diversification'?|Buying only one company.|Spreading money across many different companies and sectors.|Investing only in GICs.|Avoiding all stocks.|1|Diversification reduces 'Unsystematic' risk.|Ch 7: Investments
Which stage of the planning process involves 'Brainstorming'?|Gather|Analyze|Develop|Implement|2|The 'Development' phase is the creative design of the plan.|Ch 1: Planning Process
What is 'Inflation's' effect on a fixed-income retiree?|It makes them richer.|It reduces their purchasing power over time.|It has no effect.|It reduces their tax bill.|1|Inflation makes things more expensive while the income stays the same.|Ch 2: Economics
Which 'Mortgage' term is generally the most expensive?|5-year Fixed|1-year Variable|Open Mortgage|10-year Fixed|2|'Open' mortgages have the highest rates.|Ch 3: Mortgages
What is 'Standard Deviation'?|The average return.|A measure of how much a stock's price swings (risk).|A type of dividend.|A bank fee.|1|Higher SD means higher volatility.|Ch 7: Investments
A client earns $75,000. They have $10,000 in 'Tax Deductions.' What is their taxable income?|$65,000|$75,000|$85,000|$0|0|$75,000 - $10,000 = $65,000.|Ch 4: Taxation
Which document appoints someone to manage your 'money' while you are alive but incapacitated?|Will|Property POA|Personal Care POA|Executor|1|Property POA handles the 'finances' of the living.|Ch 10: Estate
What is 'Net Worth'?|Annual salary.|Assets minus Liabilities.|Cash in the bank.|The value of a car.|1|Net worth is a 'snapshot' of wealth.|Ch 2: Budgeting
Which 'Benefit' is based on how much you worked and contributed?|OAS|GIS|CPP|Allowance|2|CPP is a 'Contributory' plan.|Ch 8: Retirement
What is the 'Rule of 72' result for 4% return?|12 years|15 years|18 years|72 years|2|72 / 4 = 18.|Ch 5: Math
Which insurance is a 'Lump Sum' upon diagnosis?|Life|Disability|Critical Illness|Dental|2|Critical illness pays out upon survival.|Ch 9: Risk Management
What is 'Probate'?|A life insurance term.|The legal certification of a Will.|A bank charge.|A tax on the living.|1|Probate validates the Will.|Ch 10: Estate
If a client has a $300k mortgage and $500k house, what is the 'Equity'?|$200,000|$300,000|$500,000|$800,000|0|$500k - $300k = $200k.|Ch 3: Mortgages
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Monitoring is the final ongoing step.|Ch 1: Process
What is 'Suitability'?|Picking the best stock.|Matching advice to the client's risk/goals.|Charging the lowest fee.|Working for a big bank.|1|Suitability is the primary regulatory standard for advice.|Ch 11: Ethics
What is the inclusion rate for interest income?|0%|50%|75%|100%|3|Interest is 100% taxable at the marginal rate.|Ch 4: Taxation
Which 'Life Cycle' stage is Step 1?|Accumulation|Establish the Relationship|Gather Data|Consolidation|1|Step 1 of the 6 steps is establishing the relationship.|Ch 1: Process
What is 'Active' Listening?|Talking more.|Listening with the intent to understand and providing feedback.|Taking notes only.|Looking at your phone.|1|Active listening is critical for gathering accurate data.|Ch 1: Process
Which 'Indicator' is the unemployment rate?|Leading|Lagging|Coincident|Predictive|1|Unemployment changes AFTER the economy has already moved.|Ch 2: Economics`;
const set3Raw = `Amir and Sunita are purchasing a house in London, Ontario, for $625,000. They are not first-time homebuyers. Using the standard Ontario Land Transfer Tax (LTT) formula, what is the total tax they must pay at closing?|$8,975|$9,225|$10,475|$12,500|1|Calculation: 0.5% on first $55k ($275) + 1% on $55k-$250k ($1,950) + 1.5% on $250k-$400k ($2,250) + 2% on $400k-$625k ($4,500). Total: $9,225.|Ch 3: Mortgages
Marcus has a gross annual salary of $96,000. He is looking at a property with monthly property taxes of $400 and heating costs of $125. If his bank uses a 32% GDS limit, what is the maximum monthly Principal and Interest (P&I) payment he can qualify for?|$1,945|$2,035|$2,560|$3,072|1|Monthly Gross = $8,000. Max GDS = $8,000 * 0.32 = $2,560. Subtract Taxes ($400) and Heat ($125). Remaining for P&I = $2,035.|Ch 3: Mortgages
The Chen family has a $450,000 mortgage at 4.2% with 20 years remaining. They find an extra $1,000 per month in their budget. If they apply this as a 'Principal Prepayment' every month, what is the most significant long-term result?|Their monthly required payment will decrease immediately.|The interest rate on the mortgage will be reduced.|The total interest cost over the life of the loan will drop significantly and the term will shorten.|The mortgage will automatically convert to an 'Open' status.|2|Prepayments reduce the principal directly, which compounds interest savings and shortens the amortization period.|Ch 3: Mortgages
A client in the 45% marginal tax bracket sells a non-registered mutual fund for $80,000 that they originally purchased for $50,000. What is the actual 'after-tax' profit they keep from this sale?|$13,500|$16,500|$23,250|$30,000|2|Capital Gain = $30,000. Taxable portion (50%) = $15,000. Tax = $15,000 * 0.45 = $6,750. After-tax profit = Total Gain ($30,000) - Tax ($6,750) = $23,250.|Ch 4: Taxation
An advisor is meeting with a 67-year-old client who receives full OAS. The client's total net income for 2026 is expected to be $115,000. Given the 2026 OAS threshold is $95,323, how much of their OAS will be clawed back?|$2,250.00|$2,951.55|$15,000.00|$19,677.00|1|Clawback = (Income - Threshold) * 15%. ($115,000 - $95,323) * 0.15 = $2,951.55.|Ch 8: Retirement
Sarah and David earn $110,000 and $45,000 respectively. Sarah wants to gift David $20,000 to invest in a GIC earning 5%. Who is responsible for paying the tax on the $1,000 interest earned?|David, because the account is in his name.|Sarah, because of the attribution rules for spouses.|The bank, through a 15% withholding tax.|They split the tax 50/50 on their respective returns.|1|Income earned on property (like a GIC) gifted between spouses is attributed back to the donor (Sarah).|Ch 4: Taxation
A client has a $500,000 mortgage and currently pays $2,800 per month. They are considering an 'Accelerated Bi-Weekly' payment schedule. What will their new bi-weekly payment be?|$1,292.31|$1,400.00|$2,800.00|$700.00|1|Accelerated bi-weekly is the monthly payment divided by 2, paid every two weeks. $2,800 / 2 = $1,400.|Ch 3: Mortgages
A retiree has a RRIF valued at $800,000 on January 1st. They are 72 years old, and the mandatory minimum withdrawal rate is 5.40%. They withdraw $60,000. How much of this withdrawal is subject to 'Withholding Tax' at the time of payment?|$0|$16,800|$43,200|$60,000|1|Min withdrawal = $800k * 5.4% = $43,200. Only the amount ABOVE the minimum is subject to withholding tax. $60,000 - $43,200 = $16,800.|Ch 8: Retirement
An advisor identifies that a client’s portfolio has a standard deviation of 12% and an expected return of 6%. Using the concept of 'Normal Distribution,' what is the probability that the client will experience a loss in any given year?|Approximately 16%|Approximately 31%|Approximately 50%|Approximately 68%|1|One SD below the mean is 6% - 12% = -6%. In a normal distribution, ~31% of outcomes fall outside 1 SD (15.5% on the low side, 15.5% on the high side).|Ch 7: Investments
A client is purchasing a $1.2 million home. They have a $300,000 down payment. What is the minimum amount of mortgage default insurance (CMHC) they must pay?|$0|$12,400|$28,000|$40,000|0|Mortgage default insurance is not available for homes valued at $1 million or more; the buyer MUST provide at least 20% down, making it a conventional loan.|Ch 3: Mortgages
During the 'Establish the Relationship' phase, a client asks if you can guarantee a 10% return. You know that market conditions are volatile. What is the most 'Professional' and 'Objective' response?|Yes, our proprietary funds consistently hit 10% regardless of the market.|I can guarantee 10% but only if you invest in high-risk crypto assets.|While we aim for high returns, I cannot guarantee specific percentages as all investments carry risk.|I will check with my manager and get back to you with a written guarantee.|2|Professionalism and Objectivity require honesty about risk and the avoidance of false guarantees.|Ch 11: Ethics
A client has $5,000 in 'Non-Refundable' tax credits. Their calculated tax before credits is $3,500. What is their final tax position?|They get a $1,500 refund.|Their tax is reduced to $0, but the remaining $1,500 is lost.|Their tax is $0, and the $1,500 is carried forward to next year.|They pay $3,500 and get the $5,000 back later.|1|Non-refundable credits can only reduce tax to zero. They do not generate refunds or usually carry forward.|Ch 4: Taxation
An investor owns a rental property with an adjusted cost base (ACB) of $400,000. They sell it for $750,000 and incur $30,000 in real estate commissions. What is the 'Taxable Capital Gain'?|$160,000|$175,000|$320,000|$350,000|0|Capital Gain = $750k - $400k - $30k (expenses) = $320,000. Taxable portion (50%) = $160,000.|Ch 4: Taxation
A client has a $2,500 monthly mortgage, $450 car lease, and $150 minimum credit card payment. Their gross monthly income is $8,000. If they want to take out a new $300/month loan, what will their new TDS be?|31.2%|38.8%|42.5%|45.0%|1|Total Debt = $2500 + $450 + $150 + $300 = $3,400. TDS = $3,400 / $8,000 = 42.5%.|Ch 2: Consumer Lending
A client has two children, ages 4 and 6. They want to save $50,000 for each child's education using an RESP. What is the maximum total Canada Education Savings Grant (CESG) the family can receive for both children over the life of the plan?|$7,200|$10,000|$14,400|$20,000|2|The maximum lifetime grant per child is $7,200. For two children, the total is $14,400.|Ch 7: Investments
A client has a high-ratio mortgage with 15 years remaining on a 25-year amortization. They wish to 'port' their mortgage to a more expensive property. Which of the following is a standard requirement for this process?|The client must pay off the existing mortgage and pay a 3-month interest penalty.|The client must stay with the same lender and likely blend the existing rate with the current market rate.|The client must re-qualify for the entire new amount and pay for new CMHC insurance from scratch.|The client can only port the mortgage if the new property is in the same postal code.|1|Porting allows a borrower to move their existing terms and insurance to a new home, usually through a 'blend and extend' arrangement.|Ch 3: Mortgages
A client is 71 and has $400,000 in their RRSP. They want to avoid a massive tax bill. What is the most appropriate advice for Dec 31st of this year?|Withdraw the entire amount and put it in a savings account.|Convert the RRSP into a RRIF or purchase a Life Annuity.|Transfer the RRSP to their 40-year-old son tax-free.|Do nothing; the RRSP will automatically continue until age 75.|1|RRSPs must be closed or converted by the end of the year the client turns 71 to avoid the entire balance being taxed as income.|Ch 8: Retirement
Which of the following is a 'Red Flag' for money laundering according to FINTRAC guidelines?|A client asks about the management fees of a mutual fund.|A client makes a $12,000 cash deposit and asks how to avoid a reporting form.|A client requests a transfer between their own RRSP and TFSA.|A client brings their tax return to a meeting.|1|Structuring or asking how to avoid reporting requirements is a major indicator of money laundering.|Ch 12: Regulation
A client has a 'High-Ratio' mortgage with CMHC insurance. They decide to sell their home and buy a new one. Can they move the existing insurance to the new property?|No, insurance stays with the property.|Yes, through a process called 'Portability.'|Only if they stay with the same bank.|Only if the new home is cheaper than the old one.|1|CMHC and Sagen offer portability options to move insurance to a new property, saving the client money.|Ch 3: Mortgages
If a client dies without a Will (Intestate) in Ontario and has a spouse and two children, how is the first $350,000 of the estate treated?|It is split equally among the spouse and children.|The entire $350,000 goes to the spouse as a 'preferential share.'|The government takes 15% before distribution.|It is held in a trust for the children.|1|The 'Preferential Share' in Ontario (currently $350k) goes entirely to the spouse before the remainder is split.|Ch 10: Estate Planning
An advisor realizes they accidentally gave a client incorrect tax advice that led to a penalty. What is the 'Professional' action?|Ignore it and hope the client doesn't notice.|Blame the CRA for changing the rules.|Disclose the error to the client and your supervisor immediately.|Offer to pay the penalty out of your personal bank account secretly.|2|Professionalism and Integrity require immediate disclosure and following the firm’s compliance procedures.|Ch 11: Ethics
A client has $500,000 in a 'Defined Contribution' (DC) Pension. They are leaving their employer at age 50. What is the standard destination for these funds?|A regular RRSP|A Tax-Free Savings Account (TFSA)|A Locked-in Retirement Account (LIRA)|A high-interest chequing account|2|Pension funds from a DC or DB plan are usually moved to a LIRA to preserve them for retirement.|Ch 8: Retirement
What is the 'Stress Test' rate for a mortgage with a 3.5% contract rate?|3.50%|5.25%|5.50%|6.00%|2|Qualifying rate = Higher of 5.25% or (Contract Rate + 2%). 3.5 + 2 = 5.5%.|Ch 3: Mortgages
A client has a $200,000 portfolio. It is split: $100,000 in Stocks (10% return) and $100,000 in Bonds (4% return). What is the weighted average return?|6.0%|7.0%|8.0%|14.0%|1|($100k/$200k * 0.10) + ($100k/$200k * 0.04) = 0.05 + 0.02 = 7%.|Ch 7: Investments
Which of the following describes 'Systematic Risk'?|A fire at a company's main warehouse.|A CEO being arrested for fraud.|The Bank of Canada raising interest rates.|A labor strike at a specific airline.|2|Systematic risk (market risk) affects everyone and cannot be diversified away.|Ch 7: Investments
A client is in a 30% tax bracket. They receive $1,000 in 'Eligible' dividends. After the 38% gross-up and the dividend tax credit, will they pay more or less tax than on $1,000 of interest?|More tax|Less tax|Exactly the same|Dividends are tax-free|1|The Dividend Tax Credit ensures dividends are taxed more favorably than interest income.|Ch 4: Taxation
Which document gives an 'Attorney' the power to act on your behalf only AFTER you have been declared mentally incompetent?|General Power of Attorney|Enduring or Springing Power of Attorney|Last Will|Codicil|1|A 'Springing' POA only 'springs' into action upon a specific event like incapacity.|Ch 10: Estate Planning
A client has a 'Variable' mortgage where the monthly payment stays the same, but the interest rate rises. What happens to the 'Amortization'?|It shortens|It stays the same|It lengthens|It is automatically paid off by the bank|2|If the payment is fixed but interest rises, less goes to principal, so the loan takes longer to pay off.|Ch 3: Mortgages
What is the 'Primary' difference between a 'Deduction' and a 'Credit'?|Deductions are better for high-income earners; Credits are worth the same for everyone.|Credits are better for high-income earners.|They are the same thing.|Deductions are only for corporations.|0|Deductions reduce taxable income (saving at the marginal rate); credits reduce tax (saving at the lowest rate).|Ch 4: Taxation
An advisor discovers a client is using their investment account to frequently move large sums of cash to an offshore account in a high-risk jurisdiction. What is the advisor's legal obligation?|Ask the client for a larger commission.|Close the account immediately without telling anyone.|File a Suspicious Transaction Report (STR) with FINTRAC.|Call the client's spouse to warn them.|2|Advisors are 'reporting entities' and must report suspicious activity to FINTRAC.|Ch 12: Regulation
Which 'Life Cycle' stage is characterized by high debt (mortgage/student loans) and low net worth?|Early Career / Accumulation|Consolidation|Decumulation|Late Career|0|Younger clients in the early career phase typically have the highest debt-to-asset ratios.|Ch 1: Planning Process
What is the 'Probate' fee on an estate of $1,000,000 in a province where the rate is 1.5% on amounts over $50,000?|$0|$14,250|$15,000|$25,000|1|Calculation: ($1,000,000 - $50,000) * 0.015 = $14,250.|Ch 10: Estate Planning
A client has a 'Term Life' policy that is 'Convertible.' What does this mean?|They can change the beneficiary anytime.|They can switch to a permanent policy without a medical exam.|They can increase the coverage amount anytime.|The premiums stay the same forever.|1|Conversion allows a term policy to become a Whole Life or Universal Life policy regardless of health changes.|Ch 9: Risk Management
If a client has a 'GDS' of 35%, what does this imply about their mortgage application?|They are automatically approved.|They exceed the standard 32% limit and may need a larger down payment or a different lender.|They are well below the limit.|GDS doesn't matter for mortgages.|1|32% is the standard conventional limit; 35% is too high for many prime lenders.|Ch 2: Consumer Lending
A client receives $5,000 in 'Interest' and $5,000 in 'Capital Gains' in 2026. If their marginal rate is 50%, what is their total tax?|$2,500|$3,750|$5,000|$7,500|1|Interest: $5,000 * 0.5 = $2,500. Gains: ($5,000 * 0.5) * 0.5 = $1,250. Total = $3,750.|Ch 4: Taxation
Which organization provides protection for 'Bank' deposits?|Assuris|CIPF|CDIC|FCAC|2|CDIC protects deposits up to $100k per category.|Ch 12: Regulation
A client has a 'Fixed' mortgage with an 'IRD' penalty. If market rates have FALLEN since they signed, will the penalty be high or low?|Low (3 months interest)|High (based on the interest difference)|Zero|The bank pays the client|1|When market rates drop, the 'spread' the bank loses is high, resulting in a large IRD penalty.|Ch 3: Mortgages
What is the 'Attribution' rule for a gift to a MINOR child?|Income is attributed back to the donor; Capital Gains are taxed in the child's hands.|Everything is taxed in the child's hands.|Everything is attributed back to the donor.|Nothing is taxable.|0|For minors, income is attributed, but capital gains are generally taxed in the child's hands.|Ch 4: Taxation
An advisor is following the 'Diligence' principle. What does this involve?|Being friendly to the client.|Performing thorough research and providing advice in a timely manner.|Working 40 hours a week.|Charging a fair fee.|1|Diligence is about the 'effort' and 'accuracy' of the professional work.|Ch 11: Ethics
What is the 'Future Value' of $10,000 in 10 years at 0% inflation and 0% interest?|$0|$5,000|$10,000|$20,000|2|Without interest or inflation, the nominal value stays exactly the same.|Ch 5: Math
A client has $50k in a TFSA. It grows to $100k. They withdraw the full $100k. How much room do they get back next year?|$50,000|$75,000|$100,000|The original contribution only|2|You get back the FULL amount of the withdrawal (including the growth) in the following year.|Ch 5: Investments
Which stage of the 'Business Cycle' sees high inflation and high interest rates?|Trough|Expansion|Peak|Contraction|2|At the peak, the economy 'overheats,' leading to high prices and central bank rate hikes.|Ch 2: Economics
What is a 'Secondary' Will used for?|To provide for a second child.|To bypass probate on assets like private business shares in Ontario.|To replace a Will that was stolen.|To manage a house in another country.|1|Multiple Wills are a common high-end estate strategy for business owners.|Ch 10: Estate Planning
If a client has a 'Negative' Net Worth, what does this mean?|They have no assets.|Their liabilities exceed their assets.|They are in a low tax bracket.|They are a student.|1|Negative net worth means you owe more than you own.|Ch 2: Budgeting
Which 'Indicator' is the Stock Market considered?|Leading|Lagging|Coincident|Irrelevant|0|The stock market usually moves 6-9 months BEFORE the actual economy changes.|Ch 2: Economics
A client is 65 and has lived in Canada for only 15 years since age 18. How much OAS will they get?|Full OAS|15/40ths of a full pension|Nothing|A flat $100/month|1|OAS is pro-rated based on years of residence (40 years for a full pension).|Ch 8: Retirement
What is the 'Principal Residence Exemption'?|You don't pay property tax.|You don't pay capital gains tax on the sale of your primary home.|You get a free mortgage from the government.|You can deduct your mortgage interest.|1|The exemption makes the gain on your main home 100% tax-free.|Ch 4: Taxation
An advisor is asked to 'Back-date' a document to help a client qualify for a 2025 tax credit. This is:|A standard service.|A violation of the Integrity and Professionalism principles.|Fine if the client is a good friend.|Legal if the amount is under $1,000.|1|Back-dating is fraud and a major ethical/legal breach.|Ch 11: Ethics
Which insurance 'Rider' allows you to buy more coverage later without a medical exam?|Waiver of Premium|Guaranteed Insurability|Accidental Death|Term Conversion|1|The GIO (Guaranteed Insurability Option) is vital for young professionals.|Ch 9: Risk Management
What is 'Asset Allocation'?|Picking the best stock.|Determining the mix of cash, bonds, and stocks in a portfolio.|Moving everything to a TFSA.|Buying a house.|1|Allocation is the biggest factor in long-term risk and return.|Ch 7: Investments
If a client dies with no Will and no heirs, what is the term for the government taking the assets?|Probate|Escheat|Intestacy|Codicil|1|Escheat is the 'last resort' for ownerless property.|Ch 10: Estate Planning
A client has $5,000 gross monthly income. PITH is $1,800. Car is $400. What is their TDS?|28%|36%|44%|50%|2|($1,800 + $400) / $5,000 = 44%.|Ch 2: Consumer Lending
What is the 'Liquidity' of a private business?|Very High|Moderate|Very Low|Same as a stock|2|Private businesses are illiquid.|Ch 7: Investments
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|Mandat de protection (Mandate)|Codicil|Trust|Will|0|Quebec uses the 'Mandate' in case of incapacity.|Ch 10: Estate
What is the 'Nominal' rate of a loan?|The rate after inflation.|The stated or 'face' interest rate.|The rate after taxes.|The rate on a car loan.|1|Nominal is the 'advertised' rate.|Ch 5: Math
Which regulator monitors 'Investment Advisors' and 'Mutual Fund' dealers?|OSFI|CIRO|CDIC|FINTRAC|1|CIRO handles dealer conduct.|Ch 12: Regulation
A client has a $1,000 non-refundable tax credit. They are in a 40% tax bracket. How much tax do they save?|$150|$400|$600|$1,000|0|Federal non-refundable credits are calculated at the lowest bracket rate (15% - or 14% in 2026).|Ch 4: Taxation
If you are 45 and want to retire at 65, what is your 'Time Horizon'?|10 years|20 years|45 years|65 years|1|65 - 45 = 20 years.|Ch 7: Investments
What is 'Diversification'?|Buying only one company.|Spreading money across many different companies and sectors.|Investing only in GICs.|Avoiding all stocks.|1|Diversification reduces 'Unsystematic' risk.|Ch 7: Investments
Which stage of the planning process involves 'Brainstorming'?|Gather|Analyze|Develop|Implement|2|The 'Development' phase is the creative design of the plan.|Ch 1: Planning Process
What is 'Inflation's' effect on a fixed-income retiree?|It makes them richer.|It reduces their purchasing power over time.|It has no effect.|It reduces their tax bill.|1|Inflation makes things more expensive while the income stays the same.|Ch 2: Economics
Which 'Mortgage' term is generally the most expensive?|5-year Fixed|1-year Variable|Open Mortgage|10-year Fixed|2|'Open' mortgages have the highest rates.|Ch 3: Mortgages
What is 'Standard Deviation'?|The average return.|A measure of how much a stock's price swings (risk).|A type of dividend.|A bank fee.|1|Higher SD means higher volatility.|Ch 7: Investments
A client earns $75,000. They have $10,000 in 'Tax Deductions.' What is their taxable income?|$65,000|$75,000|$85,000|$0|0|$75,000 - $10,000 = $65,000.|Ch 4: Taxation
Which document appoints someone to manage your 'money' while you are alive but incapacitated?|Will|Property POA|Personal Care POA|Executor|1|Property POA handles the 'finances' of the living.|Ch 10: Estate
What is 'Net Worth'?|Annual salary.|Assets minus Liabilities.|Cash in the bank.|The value of a car.|1|Net worth is a 'snapshot' of wealth.|Ch 2: Budgeting
Which 'Benefit' is based on how much you worked and contributed?|OAS|GIS|CPP|Allowance|2|CPP is a 'Contributory' plan.|Ch 8: Retirement
What is the 'Rule of 72' result for 4% return?|12 years|15 years|18 years|72 years|2|72 / 4 = 18.|Ch 5: Math
Which insurance is a 'Lump Sum' upon diagnosis?|Life|Disability|Critical Illness|Dental|2|Critical illness pays out upon survival.|Ch 9: Risk Management
What is 'Probate'?|A life insurance term.|The legal certification of a Will.|A bank charge.|A tax on the living.|1|Probate validates the Will.|Ch 10: Estate
If a client has a $300k mortgage and $500k house, what is the 'Equity'?|$200,000|$300,000|$500,000|$800,000|0|$500k - $300k = $200k.|Ch 3: Mortgages
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Monitoring is the final ongoing step.|Ch 1: Process
What is 'Suitability'?|Picking the best stock.|Matching advice to the client's risk/goals.|Charging the lowest fee.|Working for a big bank.|1|Suitability is the primary regulatory standard for advice.|Ch 11: Ethics
What is the inclusion rate for interest income?|0%|50%|75%|100%|3|Interest is 100% taxable at the marginal rate.|Ch 4: Taxation
Which 'Life Cycle' stage is Step 1?|Accumulation|Establish the Relationship|Gather Data|Consolidation|1|Step 1 of the 6 steps is establishing the relationship.|Ch 1: Planning Process
What is 'Active' Listening?|Talking more.|Listening with the intent to understand and providing feedback.|Taking notes only.|Looking at your phone.|1|Active listening is critical for gathering accurate data.|Ch 1: Process
Which 'Indicator' is the unemployment rate?|Leading|Lagging|Coincident|Predictive|1|Unemployment changes AFTER the economy has already moved.|Ch 2: Economics`;
