const set1Raw = `According to the CSI standards, which statement best describes the recent shift in the Canadian financial services landscape?|A move toward a product-driven model focused on high-commission assets|A transition to a client-driven model where building a strong relationship is key|A focus on reducing institutional costs through automated robo-advice only|A shift toward standardized investment portfolios for all middle-market clients|1|The role of the advisor has shifted from product-driven to a client-centric model.|Ch 1: Process
An advisor is meeting with a client to discuss their retirement. The client expresses a deep-seated fear of 'running out of money' despite having a $2M portfolio. How should this be categorized?|Quantitative data as it relates to future costs|Qualitative data as it reflects the client's internal values and fears|Regulatory data required for AML compliance|Financial asset data for the net worth statement|1|Subjective feelings, goals, and fears are qualitative; hard numbers are quantitative.|Ch 1: Process
At which stage of the financial planning process must an advisor provide a written disclosure of how they are compensated for their services?|Gathering Client Data|Establishing the Client-Advisor Relationship|Analyzing and Evaluating Financial Status|Developing and Presenting Recommendations|1|Compensation disclosure is a prerequisite and must happen at the very first stage (Step 1).|Ch 1: Process
An advisor realizes they accidentally gave a client incorrect tax advice that led to a penalty. What is the most 'Professional' and 'Integrity'-based action?|Ignore it and hope the client doesn't notice|Blame the CRA for changing the rules|Disclose the error to the client and your supervisor immediately|Offer to pay the penalty out of your personal bank account secretly|2|Professionalism and Integrity require immediate disclosure and following the firm’s compliance procedures.|Ch 11: Ethics
A client has a gross monthly income of $8,000. Their monthly P&I is $2,200, property taxes are $350, and heating is $125. What is their Gross Debt Service (GDS) ratio?|27.5%|31.9%|33.4%|43.5%|2|GDS = (P+I+T+H) / Gross Monthly Income. ($2200 + $350 + $125) / $8000 = 33.43%.|Ch 2: Lending
A borrower has a gross annual salary of $90,000. He is buying a house with property taxes of $400/mo and heat of $100/mo. If the lender uses a 32% GDS limit, what is the max P&I payment he qualifies for?|$1,900|$2,400|$1,200|$2,000|0|Monthly Income = $7,500. Max GDS ($7,500 * 0.32) = $2,400. Subtract Taxes ($400) and Heat ($100). Max P&I = $1,900.|Ch 2: Lending
Which ethical principle is an advisor following when they ensure their personal prejudices do not influence the advice given to a client?|Integrity|Professionalism|Objectivity|Diligence|2|Objectivity requires the advisor to provide advice based on facts, free from personal bias.|Ch 11: Ethics
Which document is used to state medical wishes like 'Do Not Resuscitate' if a person becomes incapacitated?|Last Will|Property Power of Attorney|Living Will / Advance Directive|Trust Deed|2|Living Wills specify end-of-life medical preferences.|Ch 10: Estate Planning
A client has $5,000 in monthly expenses and wants a 6-month emergency fund. They currently have $15,000 in a HISA. What is their remaining 'Deficit' for this goal?|$5,000|$15,000|$20,000|$30,000|1|Required: $5,000 * 6 = $30,000. They have $15,000. Deficit = $15,000.|Ch 2: Budgeting
Which 'Filter' in the communication model involves the receiver's internal biases and past experiences?|Physical Filter|Psychological Filter|Language Filter|Environmental Filter|1|Psychological filters represent internal biases that change how a message is received.|Ch 1: Process
A client is crossing their arms and leaning back while you present a new investment strategy. This non-verbal cue likely signals:|Deep interest|Defensiveness or disagreement|Confusion|Agreement|1|Non-verbal cues like crossed arms often signal resistance or lack of openness.|Ch 1: Process
Which questioning technique is best for encouraging a client to share their retirement dreams?|Closed-ended questions|Open-ended questions|Leading questions|Multiple choice questions|1|'How' and 'What' questions (Open-ended) are best for gathering qualitative data.|Ch 1: Process
What is 'Equity' in the context of a family home?|The total interest paid to date|The current market value minus any outstanding mortgage debt|The original purchase price|The assessed value for property tax purposes|1|Equity is the portion of the asset truly 'owned' by the client.|Ch 3: Mortgages
If a client has a 'Negative' Net Worth, what does this mathematically imply?|They have no assets|Their total liabilities exceed their total assets|They have a low credit score|They are in the Decumulation phase|1|Negative Net Worth = Liabilities > Assets.|Ch 2: Budgeting
A borrower is purchasing a $550,000 home in Ontario. What is the total Land Transfer Tax (LTT) before any rebates?|$5,475|$7,475|$6,475|$8,475|1|0.5% on 55k ($275) + 1% to 250k ($1,950) + 1.5% to 400k ($2,250) + 2% on 150k ($3,000) = $7,475.|Ch 3: Mortgages
A first-time homebuyer in Ontario is purchasing a resale home for $400,000. What is their net Land Transfer Tax (LTT) after the first-time buyer rebate?|$475|$4,475|$0|$2,000|0|Total LTT: (55k*0.5=$275)+(195k*1%=$1,950)+(150k*1.5%=$2,250) = $4,475. Rebate is $4,000. Net = $475.|Ch 3: Mortgages
What is the standard 'Stress Test' qualifying rate for a mortgage with a contract rate of 4.5%?|4.50%|5.25%|6.50%|7.25%|2|Qualifying rate is the higher of 5.25% or the contract rate + 2% (4.5% + 2% = 6.5%).|Ch 3: Mortgages
Which mortgage feature allows a borrower to re-borrow the principal they have paid back without a new legal application?|Closed Mortgage|Fixed-Rate Mortgage|Re-advanceable Mortgage / HELOC|Convertible Mortgage|2|These allow access to equity as the principal is paid down.|Ch 3: Mortgages
A client has a $300,000 mortgage at 3.5% with 2 years remaining. If they break the mortgage and current rates are 5.5%, what is the likely penalty?|IRD (Interest Rate Differential)|3 months of interest|A flat fee of $10,000|Administrative fee only|1|If current rates are HIGHER than the contract rate, the bank usually only charges 3 months interest.|Ch 3: Mortgages
Which organization manages the 'Do Not Call' list and telecommunications privacy in Canada?|FCAC|OSFI|CRTC|CIRO|2|The CRTC regulates telecommunications conduct.|Ch 12: Regulation
A client has a $100,000 portfolio. It drops 50% ($50,000). What % gain is needed on the remaining balance to reach $100,000 again?|50%|75%|100%|200%|2|A 50% loss requires a 100% gain to break even.|Ch 7: Investments
What is 'Suitability' in the context of investment advice?|Offering the fund with the highest historical return|Ensuring the product matches the client's risk tolerance and financial goals|Ensuring the client is over 18|Matching the client's address to the account|1|Suitability is the primary regulatory standard for advice.|Ch 11: Ethics
During Step 1 of the planning process, an advisor must define the 'Scope' of work. This primarily involves:|Picking the stocks for the portfolio|Determining which areas of the client's finances will be analyzed|Collecting the client's tax returns|Implementing the insurance policy|1|Defining scope and compensation occurs in Step 1.|Ch 1: Process
Which stage of the business cycle is characterized by a peak in interest rates and slowing GDP growth?|Trough|Expansion|Peak|Contraction|2|At the peak, the economy 'overheats,' leading to higher rates.|Ch 2: Economics
What is 'Monetary Policy'?|The federal government's spending plan|Management of interest rates and money supply by the Bank of Canada|The regulation of the stock exchange|The collection of income taxes|1|The Bank of Canada uses monetary policy to control inflation.|Ch 2: Economics
Which ratio measures a client's ability to cover short-term debts using only their most liquid assets?|GDS|TDS|Current Ratio|Debt-to-Equity|2|Current Ratio = Current Assets / Current Liabilities.|Ch 2: Budgeting
A borrower is purchasing a $1.2 million home. What is the minimum down payment required by law?|$60,000|$120,000|$240,000|$300,000|2|Properties over $1M require a minimum 20% down payment as they are ineligible for CMHC insurance.|Ch 3: Mortgages
What is 'Negative Amortization'?|Paying off the principal faster than scheduled|When the monthly payment is less than the interest owed, increasing the principal balance|A decrease in the interest rate|The bank paying the borrower|1|This occurs when variable rates rise but payments remain fixed.|Ch 3: Mortgages
Which life cycle stage is characterized by peak earning power and the highest rate of debt reduction?|Early Career|Accumulation|Consolidation|Decumulation|2|Consolidation (late 40s to 50s) is the peak earning/saving period.|Ch 1: Process
A client has a target asset mix of 60% stocks and 40% bonds. After a market rally, it is 70/30. What is 'Professional' advice?|Sell bonds and buy more stocks to ride the trend|Sell stocks and buy bonds to return to the 60/40 target|Do nothing|Move everything to cash|1|Rebalancing maintain's the client's risk profile.|Ch 7: Investments
Which stage of the 6-step process involves 'Brainstorming' solutions?|Gathering Data|Analyzing Status|Developing Recommendations|Implementing the Plan|2|Developing recommendations is the 'creative' phase of the plan.|Ch 1: Process
What is a 'Fixed' expense in a monthly budget?|Grocery bill|Mortgage payment|Electricity bill|Entertainment|1|Fixed expenses are constant and often contractual.|Ch 2: Budgeting
What is the 'Marginal Tax Rate'?|The average tax paid on all income|The tax rate applied to the last dollar earned|The rate of GST|The rate of corporate tax|1|Marginal rate determines the benefit of deductions like RRSPs.|Ch 4: Taxation
If an investment has a 'Standard Deviation' of 15% and an average return of 10%, what is the range of returns for 68% of the time?|-5% to +25%|10% to 15%|-15% to +15%|0% to 16%|0|One SD (68% probability) is Mean +/- SD (10-15 and 10+15).|Ch 7: Investments
Which document handles 'End-of-Life' medical wishes like life support?|Last Will|Property POA|Living Will / Advance Directive|Trust Deed|2|These specify medical preferences during incapacity.|Ch 10: Estate Planning
Which organization protects investors if an 'Investment Dealer' (like a brokerage) goes bankrupt?|CDIC|Assuris|CIPF|FCAC|2|The Canadian Investor Protection Fund (CIPF) covers dealer insolvency.|Ch 12: Regulation
A client has a $10,000 gain on a US stock. How is this treated for Canadian tax purposes?|Taxed as interest (100%)|Taxed as a capital gain (50% inclusion)|Taxed as a dividend|Tax-free|1|Foreign capital gains are treated like Canadian capital gains.|Ch 4: Taxation
What is the 'Maximum' LTV (Loan-to-Value) for a high-ratio mortgage with default insurance?|80%|90%|95%|100%|2|With CMHC insurance, a buyer can have an LTV as high as 95% (5% down).|Ch 3: Mortgages
Which 'Trust' is created while the settlor is still alive?|Testamentary Trust|Inter Vivos Trust|Estate Trust|Executor Trust|1|Inter Vivos is Latin for 'among the living.'|Ch 10: Estate Planning
A client is 65 and has lived in Canada for only 20 years since age 18. How much OAS will they receive?|Full OAS|50% of a full pension|Nothing|A flat $500/month|1|OAS is pro-rated based on years of residence (40 years for a full pension). 20/40 = 50%.|Ch 8: Retirement
Which insurance covers a professional if they cannot perform the duties of their 'OWN' specific job?|Any Occupation Disability|Own Occupation Disability|Life Insurance|Critical Illness|1|Own Occupation is the most comprehensive disability cover.|Ch 9: Insurance
What is 'Suitability' in the context of investment advice?|Offering the highest return fund|Matching advice to the client's risk and goals|Being a licensed advisor|Working for a big bank|1|Suitability is the primary regulatory standard.|Ch 11: Ethics
Which document appoints a 'Guardian' for minor children?|Power of Attorney|Last Will and Testament|Codicil|Trust Deed|1|Guardian appointment is a critical function of the Will.|Ch 10: Estate Planning
What is 'Asset Correlation' used for in portfolio management?|Calculating total return|Determining how two investments move in relation to each other|Setting the tax rate|Determining the client's age|1|Lower correlation reduces total portfolio risk.|Ch 7: Investments
Which ratio measures a client's ability to cover short-term debts with liquid assets?|Current Ratio|Debt-to-Equity|GDS|TDS|0|Current Ratio = Current Assets / Current Liabilities.|Ch 2: Budgeting
What is 'Deflation'?|Prices going up slowly|A general decrease in the price level of goods and services|High unemployment|A drop in interest rates|1|Deflation is the opposite of inflation.|Ch 2: Economics
Which organization manages the 'Consumer Price Index' (CPI)?|Bank of Canada|CRA|Statistics Canada|OSFI|2|StatsCan tracks the basket of goods used for CPI.|Ch 2: Economics
What is a 'LIRA' (Locked-in Retirement Account)?|A type of insurance|A plan used to hold transferred pension funds|A credit card|A legal investment agreement|1|LIRAs hold pension funds that cannot be withdrawn until retirement.|Ch 8: Retirement
Which insurance covers a business if a 'Key Person' dies?|Group Life|Key Person Insurance|Workers Comp|Universal Life|1|Key Person insurance helps the business manage the loss of a vital employee.|Ch 9: Insurance
What is 'Execution' in the context of a Last Will?|The reading of the will|The legal signing and witnessing process|The distribution of money|The payment of taxes|1|A Will must be properly executed to be legally valid.|Ch 10: Estate Planning
What is 'Monetary Policy'?|Tax rate management|Management of interest rates and money supply by the Bank of Canada|Government spending|Corporate law|1|The Bank of Canada uses rates to control inflation.|Ch 2: Economics
Which 'Indicator' predicts future economic activity?|Lagging Indicator|Leading Indicator|Coincident Indicator|Trough Indicator|1|Leading indicators (like stock prices) signal where the economy is going.|Ch 2: Economics
Which type of risk is caused by a change in tax laws?|Market Risk|Interest Rate Risk|Legislative Risk|Inflation Risk|2|Legislative risk is the risk of government rule changes.|Ch 7: Investments
What is 'Real' GDP?|GDP including all sectors|GDP adjusted for inflation|GDP before taxes|GDP of the housing market|1|Real GDP accounts for inflation to show true economic growth.|Ch 2: Economics
Which stage of the 6-step process involves 'KYC' (Know Your Client)?|Step 1|Step 2|Step 4|Step 6|1|Step 2 (Gathering Data) is where the deep KYC profile is built.|Ch 1: Process
Which insurance 'Rider' pays the premiums if the insured becomes disabled?|Accidental Death|Guaranteed Insurability|Waiver of Premium|Term Conversion|2|Waiver of Premium keeps the policy in force during disability.|Ch 9: Insurance
What is the 'Federal' bottom tax rate in 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is 14%.|Ch 4: Taxation
A client has a $300,000 mortgage. They win $50,000 and pay it directly toward the principal. What is the primary impact?|The monthly payment decreases immediately|The interest rate is lowered|The amortization period is significantly shortened|The bank will charge an IRD penalty|2|Principal prepayments shorten the life of the loan.|Ch 3: Mortgages
What is the 'Nominal' rate of a loan?|The rate after inflation|The stated or 'face' interest rate|The rate after taxes|The rate on a car loan|1|Nominal is the advertised rate before adjustments.|Ch 5: Math
If a client dies with no Will and no heirs, what is the term for the government taking the assets?|Probate|Escheat|Intestacy|Codicil|1|Escheat is the last resort for ownerless property.|Ch 10: Estate Planning
What is the 'Liquidity' of a private family business?|Very High|Moderate|Very Low|Same as a stock|2|Private businesses are illiquid and hard to sell quickly.|Ch 7: Investments
Which document is the Quebec equivalent of a Power of Attorney for Personal Care?|Mandat de protection (Mandate)|Codicil|Trust|Will|0|Quebec uses the 'Mandate' in case of incapacity.|Ch 10: Estate Planning
Which regulator monitors 'Investment Advisors' and 'Mutual Fund' dealers?|OSFI|CIRO|CDIC|FINTRAC|1|CIRO (formed from IIROC and MFDA) handles dealer conduct.|Ch 12: Regulation
A client has a $1,000 non-refundable tax credit. They are in a 40% tax bracket. How much tax do they save?|$150|$400|$600|$1,000|0|Federal non-refundable credits are calculated at the lowest bracket rate (15% or 14% in 2026).|Ch 4: Taxation
If you are 45 and want to retire at 65, what is your 'Time Horizon'?|10 years|20 years|45 years|65 years|1|65 - 45 = 20 years.|Ch 7: Investments
What is 'Diversification'?|Buying only one company|Spreading money across many different companies and sectors|Investing only in GICs|Avoiding all stocks|1|Diversification reduces 'Unsystematic' risk.|Ch 7: Investments
Which stage of the planning process involves 'Brainstorming' strategies?|Gather|Analyze|Develop|Implement|2|The 'Development' phase is the strategy design phase.|Ch 1: Process
What is 'Inflation's' effect on a fixed-income retiree?|It makes them richer|It reduces their purchasing power over time|It has no effect|It reduces their tax bill|1|Inflation erodes the value of a fixed income.|Ch 2: Economics
Which 'Mortgage' term is generally the most expensive?|5-year Fixed|1-year Variable|Open Mortgage|10-year Fixed|2|'Open' mortgages have high rates for maximum flexibility.|Ch 3: Mortgages
What is 'Standard Deviation'?|The average return|A measure of how much a stock's price swings (risk)|A type of dividend|A bank fee|1|Higher SD means higher volatility.|Ch 7: Investments
A client earns $75,000. They have $10,000 in 'Tax Deductions.' What is their taxable income?|$65,000|$75,000|$85,000|$0|0|$75,000 - $10,000 = $65,000.|Ch 4: Taxation
Which document appoints someone to manage your 'money' while you are alive but incapacitated?|Will|Property POA|Personal Care POA|Executor|1|Property POA handles finances for the living.|Ch 10: Estate Planning
What is 'Net Worth'?|Annual salary|Assets minus Liabilities|Cash in the bank|The value of a car|1|Net worth is a 'snapshot' of wealth.|Ch 2: Budgeting
Which 'Benefit' is based on how much you worked and contributed?|OAS|GIS|CPP|Allowance|2|CPP is a 'Contributory' plan.|Ch 8: Retirement
What is the 'Rule of 72' result for 4% return?|12 years|15 years|18 years|72 years|2|72 / 4 = 18 years to double.|Ch 5: Math
Which insurance is a 'Lump Sum' upon diagnosis of cancer?|Life|Disability|Critical Illness|Dental|2|Critical illness pays out a survival benefit.|Ch 9: Insurance
What is 'Probate'?|A life insurance term|The legal certification of a Will|A bank charge|A tax on the living|1|Probate validates the Will for third parties.|Ch 10: Estate Planning
If a client has a $300k mortgage and $500k house, what is the 'Equity'?|$200,000|$300,000|$500,000|$800,000|0|$500k - $300k = $200k.|Ch 3: Mortgages
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Monitoring is the final ongoing step.|Ch 1: Process
Which 'Indicator' is the unemployment rate?|Leading|Lagging|Coincident|Predictive|1|Unemployment changes AFTER the economy shifts.|Ch 2: Economics
A client has $100k salary. Based on the 18% rule, how much RRSP room do they earn?|$1,000|$1,800|$18,000|$100,000|2|$100,000 * 0.18 = $18,000.|Ch 8: Retirement`;

const set2Raw = `A client in Ontario with a gross annual income of $90,000 is purchasing a $550,000 home. Their monthly property taxes are $350 and heating is $125. If they qualify for a mortgage at a 4.5% contract rate, but the benchmark stress test rate is 5.25%, which rate must the lender use to calculate their GDS ratio?|4.50%|5.25%|6.50%|7.25%|2|The qualifying rate is the higher of 5.25% or the contract rate + 2% (4.5% + 2% = 6.5%). Since 6.5% is higher than 5.25%, 6.5% is used.|Ch 3: Mortgages
Using the data from the previous question (Income: $90k/year, Taxes: $350, Heat: $125), if the calculated monthly P&I at the qualifying rate is $2,200, what is the client's GDS ratio?|29.3%|32.4%|35.7%|38.0%|2|GDS = (P&I $2,200 + Tax $350 + Heat $125) / Gross Monthly Income ($7,500). $2,675 / $7,500 = 35.66%.|Ch 2: Budgeting
A first-time homebuyer in Brampton is purchasing a resale home for $480,000. Based on the Ontario Land Transfer Tax (LTT) and the available $4,000 rebate, what is the final LTT amount they must pay at closing?|$2,075|$3,075|$6,075|$1,075|0|Total LTT: (55k*0.5%=$275) + (195k*1%=$1,950) + (150k*1.5%=$2,250) + (80k*2%=$1,600) = $6,075. Rebate = $4,000. Net = $2,075.|Ch 3: Mortgages
A client earns $120,000 in 2026. If the federal tax brackets are 14% on the first $58,523 and 20.5% on the next $58,522, what is the federal tax payable on the portion of income that falls strictly into the second bracket?|$8,193|$11,997|$12,400|$24,600|1|The second bracket is the income between $58,523 and $117,045. $58,522 * 0.205 = $11,997.01.|Ch 4: Taxation
A retiree's net world income for 2026 is $105,000. Given the OAS recovery tax threshold is $95,323, how much of their annual OAS pension must they repay?|$1,451.55|$2,250.00|$4,500.00|$9,677.00|0|Clawback = 15% of (Income - Threshold). ($105,000 - $95,323) * 0.15 = $1,451.55.|Ch 8: Retirement
In 2026, an employee earns $85,000. Based on a YMPE of $74,600 and a YAMPE of $85,000, which portion of their income is subject to the 'CPP2' (second-tier) contribution rate of 4%?|$0 (They are below the threshold)|$10,400|$74,600|$85,000|1|CPP2 applies to earnings between the YMPE ($74,600) and the YAMPE ($85,000). $85,000 - $74,600 = $10,400.|Ch 8: Retirement
A client has $20,000 of 'unused' RRSP room from previous years. In 2025, they earned $100,000. In 2026, they want to maximize their contribution. Ignoring any pension adjustment, what is their total 2026 deduction limit?|$18,000|$33,810|$38,000|$53,810|2|2026 Limit = 18% of 2025 income ($18,000) + Carry-forward ($20,000) = $38,000. (Since $18k is less than the $33,810 cap).|Ch 8: Retirement
An investor in a 40% marginal tax bracket receives $3,000 in Canadian eligible dividends. If the gross-up is 38% and the combined dividend tax credit is 25% of the grossed-up amount, what is the net tax payable?|$35|$120|$210|$1,200|2|Grossed-up = $4,140. Tax before credit = $4,140 * 0.40 = $1,656. Credit = $4,140 * 0.25 = $1,035. Net tax = $621.|Ch 4: Taxation
A client dies intestate in Ontario leaving a spouse and two children. The net value of the estate is $500,000. How is the estate distributed?|Spouse gets $500,000|Spouse gets $350,000; Children split $150,000|Spouse gets $400,000; Children split $100,000|Spouse gets $166,666; Children split $333,334|2|Ontario Preferential Share = $350,000 to spouse. Remainder ($150k) is split: 1/3 to spouse ($50k) and 2/3 to kids ($100k). Total for spouse: $400k.|Ch 10: Estate
Which of the following is true regarding a 'High-Ratio' mortgage for a property valued at $1,200,000?|The borrower can pay 5% down if they have CMHC insurance.|A minimum 20% down payment is required as insurance is not available over $1M.|The stress test is waived for homes of this value.|The borrower can use a 35-year amortization to qualify.|1|Default insurance (CMHC/Sagen) is only available on homes under $1,000,000. Over $1M requires at least 20% down.|Ch 3: Mortgages
A client has $5,000 in monthly expenses and $50,000 in a TFSA. They wish to maintain a 6-month emergency fund in cash. How should this be reflected on their Net Worth statement?|$30,000 as a Liability; $20,000 as an Asset|$50,000 as a Liquid Asset|$30,000 as a Liquid Asset; $20,000 as an Investment Asset|It should not be listed on the Net Worth statement|2|The emergency fund portion ($30k) is liquid; the remainder of the TFSA is an investment asset.|Ch 2: Budgeting
A borrower has a 5-year fixed mortgage at 3%. They want to break the mortgage with 2 years left. Current 2-year rates are 5%. What is the likely penalty?|The Interest Rate Differential (IRD)|3 months of interest|A flat fee of $1,000|1% of the principal balance|1|When current rates are higher than the contract rate, banks typically charge the '3-month interest' penalty as there is no IRD loss.|Ch 3: Mortgages
An investor buys a 'Strip Bond' for $600 with a face value of $1,000 maturing in 10 years. How is the $400 gain treated for tax purposes?|As a capital gain in the year it matures|As interest income that must be reported annually (Accrual)|As a tax-free gift|As a dividend|1|The 'interest' (discount) on a strip bond must be reported annually as if it were paid, even though it isn't.|Ch 4: Taxation
A client has a $10,000 capital loss from 2025. In 2026, they have $4,000 in interest income and $6,000 in capital gains. Can they use the loss to reduce their 2026 tax bill?|Yes, they can offset the $4,000 interest.|Yes, they can offset the $6,000 capital gain.|No, losses can only be carried back.|Yes, they can offset all $10,000 of income.|1|Capital losses can only be used to offset capital gains, not interest or employment income.|Ch 4: Taxation
An advisor is asked by a long-time client to 'adjust' the date on an insurance application to ensure coverage starts before a medical diagnosis. What is the correct course of action?|Perform the request as a courtesy to a loyal client.|Decline and explain that this is a violation of the 'Integrity' principle.|Only do it if the manager approves.|Perform the request but don't sign the document yourself.|1|Integrity and Professionalism prohibit any form of fraud or back-dating.|Ch 11: Ethics
A client has $500,000 in a 'Joint Account' with their spouse at a Big Five bank. If the bank fails, how much is covered by CDIC?|$100,000|$200,000|$250,000|$500,000|0|CDIC provides $100,000 coverage per member institution for the category of 'Joint Accounts' (not per person).|Ch 12: Regulation
Which life insurance policy allows the owner to choose the underlying investment sub-accounts (e.g., Equity or Bond funds)?|Whole Life|Term Life|Universal Life|Group Life|2|Universal Life is 'unbundled' and allows the owner to manage the investment portion.|Ch 9: Risk
If a client has a 'Variable' rate mortgage with 'Fixed Payments,' what happens if interest rates rise above the 'Trigger Point'?|The bank closes the mortgage.|The monthly payment no longer covers the interest, and the principal balance begins to increase.|The interest rate is automatically locked in as a fixed rate.|The government pays the difference.|1|This is 'Negative Amortization,' where the debt grows because payments don't cover interest.|Ch 3: Mortgages
A client is in a 40% tax bracket and receives $1,000 in 'Interest' income. How much 'After-Tax' cash do they keep?|$400|$600|$850|$1,000|1|$1,000 minus (1,000 * 0.40) = $600.|Ch 4: Taxation
What is the 'Rule of 72' result if a client wants to double their money in 6 years?|6%|8%|10%|12%|3|72 / 6 = 12% return required.|Ch 5: Math
A client has $100,000 in a LIRA. They are 55 and want to withdraw $10,000 for a vacation. Is this allowed?|Yes, with a 20% tax.|Only if they have a spouse's permission.|No, LIRA funds are locked until retirement age with very few exceptions.|Yes, if they replace the money within 10 years.|2|LIRAs (Locked-in Retirement Accounts) are designed to provide a lifetime income and are strictly controlled.|Ch 8: Retirement
Which investment is most suitable for a 3-month 'Emergency Fund'?|Common Stocks|5-year GIC|High-Interest Savings Account (HISA)|Real Estate|2| HISAs offer safety of principal and immediate liquidity.|Ch 2: Budgeting
A client's house is worth $800,000 and they have a $400,000 mortgage. What is their 'Loan-to-Value' (LTV) ratio?|25%|40%|50%|200%|2|LTV = $400k / $800k = 50%.|Ch 3: Mortgages
If the 'Stress Test' rate is 5.25% and your contract rate is 6%, what is your 'Qualifying' rate?|5.25%|6.00%|7.25%|8.00%|3|Qualifying rate is the higher of 5.25% or (Contract + 2%). 6 + 2 = 8%.|Ch 3: Mortgages
A client has $10,000 in a TFSA. They lose $5,000 on a bad stock. How much room do they lose?|$0|$5,000|$10,000|The room is frozen|1|TFSA room is based on the 'market value' at withdrawal. If the value drops, that room is effectively lost.|Ch 5: Investments
A client receives $5,000 in 'Interest' and $5,000 in 'Capital Gains' in 2026. If their marginal rate is 50%, what is their total tax?|$2,500|$3,750|$5,000|$7,500|1|Interest: $5,000 * 0.5 = $2,500. Gains: ($5,000 * 0.5) * 0.5 = $1,250. Total = $3,750.|Ch 4: Taxation
If an investment has a 'Standard Deviation' of 15% and an average return of 8%, what is the range of returns for 68% of the time?|-7% to +23%|8% to 15%|-15% to +15%|0% to 16%|0|One standard deviation (68% probability) is Mean +/- SD (8-15 and 8+15).|Ch 7: Investments
A client earns $75,000. They have $10,000 in 'Tax Deductions.' What is their taxable income?|$65,000|$75,000|$85,000|$0|0|$75,000 - $10,000 = $65,000.|Ch 4: Taxation
A borrower is purchasing a $300,000 property. They have a $30,000 down payment. What is the amount of the mortgage loan?|$270,000|$300,000|$330,000|$30,000|0|$300,000 - $30,000 = $270,000.|Ch 3: Mortgages
A client wants to ensure their children receive $100,000 in 15 years. If the interest rate is 6%, what is the required PV?|$41,726|$50,000|$62,500|$84,000|0|PV = $100,000 / (1.06)^15 = $41,726.51.|Ch 5: Math
Which of the following describes a 'Convertible' mortgage?|A mortgage that can be switched to a different property|A variable rate mortgage that can be changed to a fixed rate without penalty|A mortgage that becomes a line of credit|A mortgage that converts to a rental loan|1|Convertible mortgages offer the ability to lock in a fixed rate if rates begin to rise.|Ch 3: Mortgages
A client sells a painting for $5,000 that they bought for $500. How much is the capital gain?|$5,000|$4,500|$2,500|$2,250|1|$5,000 - $500 = $4,500.|Ch 4: Taxation
A couple is buying a $950,000 home. What is the minimum down payment required?|$47,500|$70,000|$190,000|$95,000|1|5% on first $500k ($25k) + 10% on next $450k ($45k). Total = $70,000.|Ch 3: Mortgages
A client has a $400,000 mortgage. The lender allows a 15% 'Annual Prepayment.' How much can they pay extra this year?|$15,000|$40,000|$60,000|$100,000|2|$400,000 * 0.15 = $60,000.|Ch 3: Mortgages
An investor earns $1,000 in interest in a TFSA. How much tax do they owe on this?|$0|$150|$400|$500|0|Income and gains within a TFSA are 100% tax-free.|Ch 5: Investments
A client withdraws $5,000 from their RRSP under the 'Lifelong Learning Plan.' When must they start repaying it?|Immediately|In 2 years|In 5 years|In 10 years|2|LLP repayments typically begin in the fifth year after the first withdrawal.|Ch 8: Retirement
Which of the following is 'Excluded' from the calculation of Net Income?|Tips and Gratuities|Lottery Winnings|Spousal Support Received|Net Rental Income|1|Lottery winnings and most gifts/inheritances are non-taxable in Canada.|Ch 4: Taxation
A client is in a 30% tax bracket. They contribute $10,000 to an RRSP. What is the tax savings?|$1,000|$3,000|$4,000|$10,000|1|$10,000 * 0.30 = $3,000.|Ch 4: Taxation
What is the 'Effective' rate of a 10% loan compounded semi-annually?|10.00%|10.25%|10.50%|11.00%|1|Effective Rate = (1 + 0.05)^2 - 1 = 10.25%.|Ch 5: Math
Which mortgage option is most suitable for a client who plans to sell their home in 6 months?|5-year Fixed Closed|5-year Variable Closed|6-month Open|10-year Fixed|2|Open mortgages have higher rates but no penalty for early payout.|Ch 3: Mortgages
A client has a $200,000 mortgage and a $50,000 car loan. Their home is worth $500,000. What is their 'Debt-to-Asset' ratio?|10%|40%|50%|60%|2|Total Debt ($250k) / Total Assets ($500k) = 50%.|Ch 2: Budgeting
What is the impact of choosing a 25-year amortization instead of a 20-year?|Lower monthly payments; lower interest cost|Higher monthly payments; lower interest cost|Lower monthly payments; higher interest cost|Higher monthly payments; higher interest cost|2|Extending amortization reduces the monthly 'hit' but increases total interest paid.|Ch 3: Mortgages
A client receives a $10,000 dividend from a US corporation. How is this taxed in Canada?|With the dividend tax credit|As interest income (100% inclusion)|As a capital gain|Tax-free|1|Foreign dividends do not qualify for the Canadian dividend tax credit.|Ch 4: Taxation
Which of the following is a 'Qualitative' goal?|I want to have $1M by age 65|I want to travel every winter|I want to feel financially independent from my employer|Both B and C|3|Subjective desires and feelings are qualitative.|Ch 1: Process
A client has a 5-year mortgage term. What happens at the end of the 5 years?|The mortgage is fully paid off|The borrower must renew or pay the remaining balance|The interest rate stays the same forever|The bank takes the house|1|The term is the duration of the current interest rate contract.|Ch 3: Mortgages
If a client has a 'High' risk tolerance but a 'Short' time horizon (2 years), what is the most suitable investment?|100% Equity|Growth Mutual Fund|Balanced Fund|GIC or Money Market|3|Time horizon is the primary constraint; short terms require safety.|Ch 7: Investments
What is the federal 'Basic Personal Amount' for 2026?|$15,000|$16,200|$18,000|$20,000|1|The BPA is indexed annually; for 2026 it is approximately $16,200.|Ch 4: Taxation
Which organization provides protection for 'Investment' accounts if a dealer fails?|CDIC|Assuris|CIPF|FCAC|2|CIPF covers up to $1 million per account category.|Ch 12: Regulation
A client has a $2,000 capital gain and a $3,000 capital loss in the same year. What is their 'Net' taxable gain?|$0|$1,000|$2,000|-$1,000|0|Capital losses must be applied against capital gains. The net is $0.|Ch 4: Taxation
Which document appoints a 'Guardian' for minor children?|Power of Attorney|Will|Codicil|Trust Deed|1|The Will is the only legal document for appointing guardians.|Ch 10: Estate
What is the 'Real' rate of return if nominal is 5% and inflation is 2%?|2%|3%|5%|7%|1|5% - 2% = 3%.|Ch 5: Math
Which stage of the 6-step process involves 'KYC' forms?|Step 1|Step 2|Step 3|Step 4|1|Step 2 is the data gathering and profile building phase.|Ch 1: Process
What is 'Suitability'?|Picking the best stock|Matching advice to risk and goals|Charging the lowest fee|Working for a big bank|1|The core regulatory standard for advisors.|Ch 11: Ethics
A client has a $5,000 GDS. Their income is $15,000. Is this acceptable?|Yes|No|Only if they have no other debt|Only if they are rich|1|GDS is 33.3%, which exceeds the typical 32% threshold.|Ch 2: Lending
Which insurance pays if you can't do your OWN job?|Any Occ|Own Occ|Life|Critical Illness|1|Own Occupation is the most comprehensive definition.|Ch 9: Insurance
What is 'Inflation'?|Prices going down|Prices going up and purchasing power falling|Interest rates rising|Stock prices rising|1|Inflation erodes the value of money.|Ch 2: Economics
Which 'Trust' starts AFTER death?|Inter Vivos|Testamentary|Family|Revocable|1|Testamentary trusts are built into the Will.|Ch 10: Estate
What is the RRSP 'Earned Income' inclusion rate?|10%|15%|18%|20%|2|RRSP room grows by 18% of the previous year's earned income.|Ch 8: Retirement
Which benefit is for 'low-income' seniors?|CPP|OAS|GIS|PRPP|2|GIS is a supplement for those with little other income.|Ch 8: Retirement
If a client dies 'Intestate', who decides distribution?|The Bank|The Family|Provincial Law|The CRA|2|Intestacy triggers the provincial succession formula.|Ch 10: Estate
What is 'Diversification'?|Buying one stock|Spreading money to reduce unsystematic risk|Investing in GICs only|Avoiding the market|1|Diversification reduces the risk of a single company failing.|Ch 7: Investments
Which stage is Step 5?|Analyze|Develop|Implement|Monitor|2|Implementation is the action phase.|Ch 1: Process
A client wins $10,000 on a scratch ticket. How is it taxed?|100% taxable|50% taxable|Tax-free|30% withholding|2|Lottery and gambling winnings are non-taxable in Canada.|Ch 4: Taxation
What is 'Net Worth'?|Annual salary|Assets - Liabilities|Cash in bank|Value of home|1|The total value of what you own minus what you owe.|Ch 2: Budgeting
Which 'Indicator' is the stock market?|Leading|Lagging|Coincident|Predictive|0|The market often moves before the economy shifts.|Ch 2: Economics
A client is 71. What must they do with their RRSP?|Withdraw all|Convert to RRIF or Annuity|Give it to kids|Nothing|1|Conversion must happen by Dec 31 of age 71.|Ch 8: Retirement
What is the inclusion rate for 'Interest' income?|0%|50%|75%|100%|3|Interest is fully taxable at the marginal rate.|Ch 4: Taxation
Which document handles 'Property' while alive?|Will|Property POA|Personal Care POA|Executor|1|POA Property handles finances during incapacity.|Ch 10: Estate
What is the 'Rule of 72' for 9% return?|4 years|8 years|9 years|12 years|1|72 / 9 = 8 years.|Ch 5: Math
Which insurance is for a 'Survival' of an illness?|Life|Disability|Critical Illness|Dental|2|Critical illness pays a lump sum if you survive.|Ch 9: Insurance
What is 'Probate'?|Life insurance claim|Legal certification of a Will|Bank fee|Tax on living|1|Probate validates the Will.|Ch 10: Estate
If a house is $500k and mortgage is $300k, equity is?|$200k|$300k|$500k|$800k|0|$500k - $300k = $200k.|Ch 3: Mortgages
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Monitoring is the final ongoing step.|Ch 1: Process
Which 'Indicator' is unemployment?|Leading|Lagging|Coincident|Predictive|1|Unemployment changes after the economy shifts.|Ch 2: Economics
What is the 'Federal' bottom tax rate 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is 14%.|Ch 4: Taxation
A client has $100k salary. Max RRSP room 2026?|$18k|$30k|$33,810|$100k|2|The cap for 2026 is $33,810.|Ch 8: Retirement
Which insurance covers ANY job you are suited for?|Own Occ|Any Occ|Critical Illness|Term|1|Any Occupation is a stricter, cheaper definition.|Ch 9: Insurance
A client earns $4,000/mo and PITH is $1,200. GDS?|25%|30%|35%|40%|1|$1,200 / $4,000 = 30%.|Ch 2: Lending
What is 'Nominal' rate?|After inflation|Face/Stated rate|After tax|Car loan rate|1|Nominal is the stated annual interest rate.|Ch 5: Math
If someone dies without a Will, they die?|Testate|Intestate|Probated|Escheated|1|Intestacy is the state of dying without a Will.|Ch 10: Estate
What is 'Execution' of a Will?|Reading it|Signing/Witnessing|Paying taxes|Distributing money|1|The formal legal signing process.|Ch 10: Estate`;

const set3Raw = `An investor holds a portfolio with a Beta of 1.2. If the market rises by 10%, what is the expected return of this portfolio, assuming no unsystematic risk?|8.0%|10.0%|12.0%|15.0%|2|Beta measures sensitivity to the market. 10% * 1.2 = 12%.|Ch 7: Investments
A client has $500,000 in a RRIF on January 1st, 2026. They are 72 years old. If the mandatory minimum withdrawal rate is 5.40%, and they withdraw $40,000, how much withholding tax will the bank deduct at source?|$0|$1,500|$3,000|$8,000|0|Withholding tax is only applied to amounts ABOVE the minimum. The minimum is $27,000. Since $40k is withdrawn, $13k is 'excess' and subject to tax, but the first $27k is $0 tax at source.|Ch 8: Retirement
Which of the following describes the 'Standard Deviation' of a mutual fund that has highly volatile returns compared to its mean?|Low Standard Deviation|High Standard Deviation|Zero Standard Deviation|Negative Standard Deviation|1|Standard Deviation measures the 'spread' of returns; wider swings result in a higher SD.|Ch 7: Investments
A client is 62 and wants to start their CPP early. By what total percentage will their pension be reduced if the monthly reduction rate is 0.6%?|7.2%|14.4%|21.6%|36.0%|2|36 months early (65 - 62) * 0.6% = 21.6% reduction.|Ch 8: Retirement
An investor in the 50% marginal bracket sells a stock for $100,000 (Cost: $60,000). Two months later, they sell a different stock for $20,000 (Cost: $30,000). What is their net taxable capital gain for the year?|$5,000|$15,000|$20,000|$30,000|1|Gain of $40k - Loss of $10k = $30k net gain. Inclusion rate is 50%, so $15,000 is taxable.|Ch 4: Taxation
Which life insurance policy is 'unbundled,' allowing the client to see the specific costs of insurance, administrative fees, and investment returns separately?|Whole Life|Term Life|Universal Life|Group Life|2|Universal Life is transparent and unbundled, unlike Whole Life.|Ch 9: Insurance
A client has a 'Segregated Fund' with a 75% maturity guarantee. They invest $100,000. In 10 years, the market value is $60,000. How much will the client receive?|$60,000|$75,000|$100,000|$110,000|1|The 75% guarantee ensures they receive at least $75,000 at maturity.|Ch 9: Insurance
An executor is managing an estate with a $2M private business and $1M in cash. Why might they choose to file a 'Secondary Will' in Ontario?|To avoid paying federal income tax|To bypass the 1.5% Estate Administration Tax (Probate) on the $2M business|To hide assets from the heirs|To speed up the funeral arrangements|1|In Ontario, multiple wills allow private assets to bypass the probate fee.|Ch 10: Estate
What is the 'Maximum' annual contribution for the First Home Savings Account (FHSA) in 2026?|$5,000|$8,000|$18,000|$40,000|1|The annual limit is $8,000, with a lifetime max of $40,000.|Ch 4: Taxation
A client has a $500,000 Term-10 life policy. In year 11, the policy 'renews.' What is the most likely outcome?|The coverage ends|The premiums increase significantly based on the client's new age|The premiums stay the same|The policy converts to Whole Life automatically|1|Term policies renew at a much higher cost because the risk of death is higher at the older age.|Ch 9: Insurance
Which type of 'Power of Attorney' only becomes active once a medical professional declares the donor mentally incapable?|General POA|Enduring POA|Springing POA|Codicil|2|A 'Springing' POA is triggered (springs into effect) by a specific event like incapacity.|Ch 10: Estate
A client has $200,000 in a LIRA from a previous employer. They are now 58 and experiencing 'Financial Hardship.' Can they access this money?|No, never|Only if they have a doctor's note|Yes, under specific provincial 'Unlocking' rules for low income or medical debt|Yes, they can withdraw it like a TFSA|2|Provinces allow limited unlocking of LIRAs for specific hardship categories.|Ch 8: Retirement
Which investment would have the highest 'Correlation' (+1.0) with a Canadian Equity Mutual Fund?|A Gold ETF|A US S&P 500 Index Fund|A Government of Canada Bond|A Savings Account|1|Equity markets often move together; Gold and Bonds usually have low or negative correlation.|Ch 7: Investments
What is the 'Stop-Loss' provision in a health insurance policy?|The maximum the insurance company will pay|The maximum amount of covered expenses the insured must pay out-of-pocket annually|The amount of the deductible|The date the policy expires|1|Once the stop-loss is hit, the insurer pays 100% of remaining covered costs.|Ch 9: Insurance
A client is in the 50% tax bracket. They earn $1,000 in 'Interest' and $1,000 in 'Capital Gains.' What is the total tax?|$500|$750|$1,000|$1,500|1|Interest ($500 tax) + Gain ($250 tax, due to 50% inclusion) = $750.|Ch 4: Taxation
In a 'Successor Annuitant' designation for a RRIF, what happens when the primary owner dies?|The account is collapsed and taxed|The surviving spouse becomes the new owner and payments continue seamlessly|The money goes to the children tax-free|The estate pays probate on the balance|1|Successor Annuitant (spouse only) allows for a direct continuation of the RRIF.|Ch 10: Estate
Which of the following is an example of 'Unsystematic' risk?|A change in the national interest rate|A global pandemic|A massive fraud discovery at a specific technology company|Inflation rising to 5%|2|Specific risk (unsystematic) can be diversified away by holding many different stocks.|Ch 7: Investments
A 65-year-old client has a net income of $120,000. If the OAS clawback threshold is $95,323, what is the 'Recovery Tax'?|$2,500.00|$3,701.55|$15,000.00|$0|1|Calculation: ($120,000 - $95,323) * 0.15 = $3,701.55.|Ch 8: Retirement
What is the primary difference between a 'Testamentary' Trust and an 'Inter Vivos' Trust?|The tax rate applied|One is created in a Will; the other while the person is alive|The type of assets they can hold|The number of beneficiaries|1|Testamentary is triggered by death; Inter Vivos is 'among the living.'|Ch 10: Estate
Which disability definition pays out if the insured cannot perform the duties of 'ANY' occupation for which they are reasonably suited by education/experience?|Own Occupation|Any Occupation|Presumptive Disability|Residual Disability|1|'Any Occupation' is a stricter definition and usually results in lower premiums.|Ch 9: Insurance
A client has $50,000 in an RRSP and $50,000 in a TFSA. They need $20,000 for a car. Which withdrawal is generally better for a client in a high tax bracket?|The RRSP|The TFSA|Both are the same|Neither, they should use a credit card|1|TFSA withdrawals are tax-free; RRSP withdrawals are taxed at the high marginal rate.|Ch 4: Taxation
An investor buys a bond for $1,050 (Face Value $1,000) with a 5% coupon. Is the 'Yield to Maturity' (YTM) higher or lower than 5%?|Higher|Lower|The same|Exactly 10%|1|Because they paid a 'premium' ($1,050), the total yield will be lower than the stated coupon.|Ch 7: Investments
Which document allows you to appoint someone to make medical decisions if you are in a coma?|Property POA|Last Will|Personal Care POA / Proxy|Trust Deed|2|Personal Care POAs handle health and lifestyle, not money.|Ch 10: Estate
A client wants to save $1M for retirement in 30 years. If they have $100k today and earn 6%, what is the required annual 'PMT' deposit?|$7,200|$9,450|$12,330|$15,000|1|Financial Calculator: N=30, I=6, PV=-100000, FV=1000000, solve for PMT.|Ch 5: Math
What is 'Probate'?|A tax on the living|A legal process to certify the validity of a Will|A life insurance rider|A type of retirement plan|1|Probate gives the executor the 'legal' authority to act.|Ch 10: Estate
Which organization protects policyholders if a Life Insurance company fails?|CDIC|Assuris|CIPF|FCAC|1|Assuris is the 'safety net' for the life insurance industry.|Ch 12: Regulation
A client is in the 30% tax bracket. They have $2,000 in 'Eligible' dividends. Which will result in the LOWEST tax?|$2,000 Interest|$2,000 Capital Gains|$2,000 Eligible Dividends|They are all the same|1|Capital gains have a 50% inclusion rate, making the effective tax 15% (vs 30% for interest).|Ch 4: Taxation
A client has an 'Own Occupation' disability policy. They are a surgeon who loses a finger and can no longer perform surgery, but they can still teach at a university. Will the policy pay?|No, because they can still teach|Yes, because they cannot perform their specific 'own' job|Only for 2 years|Only if they have no other income|1|Own Occupation pays if you cannot do the job you were trained for.|Ch 9: Insurance
What is the 'Rule of 72' result for an investment earning 4%?|12 years|18 years|24 years|72 years|1|72 / 4 = 18 years to double.|Ch 5: Math
A client has a $500k house and $200k mortgage. If they die, which insurance is designed to pay off the debt specifically?|Whole Life|Term Life / Creditor Insurance|Critical Illness|Disability|1|Term or Creditor insurance covers temporary debt obligations.|Ch 3: Mortgages
Which stage of the 6-step process involves 'KYC' and risk profile questionnaires?|Step 1|Step 2|Step 3|Step 4|1|Data gathering (Step 2) includes building the client profile.|Ch 1: Process
A client has a 40% marginal rate. They receive $5,000 in 'Interest.' How much tax is owed?|$1,000|$1,500|$2,000|$2,500|2|Interest is 100% taxable at the marginal rate ($5k * 0.4).|Ch 4: Taxation
What is 'Asset Allocation'?|Picking a hot stock|The mix of cash, bonds, and stocks in a portfolio|Using a TFSA instead of an RRSP|Buying a house|1|Asset allocation determines most of the risk and return.|Ch 7: Investments
Which document handles your medical wishes if you cannot speak for yourself?|Will|Property POA|Living Will / Advance Directive|Codicil|2|Advance directives cover 'end of life' choices.|Ch 10: Estate
A client dies with no Will and no relatives. Who gets the assets?|The Bank|The CRA|The Provincial Government (Escheat)|The United Nations|2|Escheat is the process where ownerless property returns to the Crown.|Ch 10: Estate
Which investment is most suitable for a 1-year time horizon?|Common Stocks|Emerging Market Fund|GIC or HISA|Real Estate|2|Short timelines require safety of principal.|Ch 7: Investments
What is 'Inflation'?|Prices going down|The decrease in purchasing power over time|The stock market rising|Interest rates falling|1|Inflation means your dollar buys less today than yesterday.|Ch 2: Economics
Which organization manages the 'Consumer Price Index' (CPI)?|Bank of Canada|CRA|Statistics Canada|OSFI|2|StatsCan tracks the basket of goods used for inflation.|Ch 2: Economics
A client has $100k in a TFSA. It drops to $40k. They withdraw the $40k. How much room do they get back next year?|$40,000|$60,000|$100,000|Only the original contribution|0|You get back exactly what you withdrew. If the value dropped, that room is gone.|Ch 5: Investments
Which stage of the planning process is Step 5?|Analyze|Develop|Implement|Monitor|2|Implementation is the 'Action' step.|Ch 1: Process
What is 'Suitability'?|Matching advice to risk and goals|Picking the best stock|Being a licensed advisor|Charging low fees|0|Suitability is the core regulatory requirement for advice.|Ch 11: Ethics
What is the federal bottom tax rate for 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is 14%.|Ch 4: Taxation
A client wins $10,000 in a lottery. How is it taxed?|100% taxable|50% taxable|Tax-free|30% withholding|2|Lottery/Gambling winnings are non-taxable in Canada.|Ch 4: Taxation
Which document handles 'Property' and money while you are alive but incapable?|Will|Property POA|Personal Care POA|Executor|1|POA Property handles finances for the living.|Ch 10: Estate
What is 'Net Worth'?|Annual salary|Assets minus Liabilities|Cash in the bank|Value of your car|1|Total owned minus total owed.|Ch 2: Budgeting
Which 'Benefit' is based on contributions from your paycheck?|OAS|GIS|CPP|Allowance|2|CPP is a contributory pension.|Ch 8: Retirement
Which insurance pays a 'Lump Sum' if you survive a heart attack?|Life|Disability|Critical Illness|Dental|2|Critical illness is a survival benefit.|Ch 9: Insurance
If a house is $600k and the mortgage is $400k, equity is?|$200,000|$400,000|$600,000|$1,000,000|0|$600k - $400k = $200k.|Ch 3: Mortgages
Which 'Stage' is Step 6?|Gather|Analyze|Monitor|Implement|2|Monitoring is the final ongoing step.|Ch 1: Process
Which 'Indicator' is the stock market?|Leading|Lagging|Coincident|Predictive|0|The market often moves before the economy shifts.|Ch 2: Economics
What is 'Probate'?|Life insurance term|Legal certification of a Will|Bank fee|Tax on living|1|Probate validates the Will.|Ch 10: Estate
A client has $100k salary. Max RRSP room 2026?|$18,000|$30,000|$33,810|$100,000|2|The 2026 RRSP cap is $33,810.|Ch 8: Retirement
Which insurance covers ANY job you are suited for?|Own Occ|Any Occ|Critical Illness|Term|1|Any Occupation is a stricter, cheaper definition.|Ch 9: Insurance
A client earns $4,000/mo and PITH is $1,200. GDS?|25%|30%|35%|40%|1|$1,200 / $4,000 = 30%.|Ch 2: Lending
What is 'Nominal' rate?|After inflation|Face/Stated rate|After tax|Car loan rate|1|Nominal is the stated annual interest rate.|Ch 5: Math
If someone dies without a Will, they die?|Testate|Intestate|Probated|Escheated|1|Intestacy is the state of dying without a Will.|Ch 10: Estate
What is 'Execution' of a Will?|Reading it|Signing/Witnessing|Paying taxes|Distributing money|1|The formal legal signing process.|Ch 10: Estate
A borrower is purchasing a $1.2M home. What is the min down payment?|$60,000|$120,000|$240,000|$300,000|2|Homes over $1M require 20% down ($240k).|Ch 3: Mortgages
What is the 'Inclusion Rate' for capital gains?|0%|50%|75%|100%|1|Individuals include 50% of the gain in income.|Ch 4: Taxation
Which document amends a Will?|Power of Attorney|Codicil|Letter of Intent|Living Will|1|A codicil is a formal amendment.|Ch 10: Estate
Which organization regulates bank 'solvency'?|CIRO|OSFI|CDIC|FCAC|1|OSFI monitors financial health.|Ch 12: Regulation
A client has a 20% down payment on a $600k home. Is insurance mandatory?|Yes|No|Only if variable|Only for first-timers|1|Conventional (20% down) doesn't need CMHC.|Ch 3: Mortgages
What is the 'Rule of 72' for 6% return?|6 years|8 years|12 years|15 years|2|72 / 6 = 12 years.|Ch 5: Math
Which stage of the cycle sees peak interest rates?|Trough|Expansion|Peak|Contraction|2|Peak is the top of the cycle.|Ch 2: Economics
What is a 'LIRA'?|Locked-in Retirement Account|Insurance Risk|Interest Adjustment|Legal Agreement|0|Holds pension funds.|Ch 8: Retirement
Which is a 'Qualitative' data point?|Income|Debt|Retirement Goals|Net Worth|2|Goals are qualitative.|Ch 1: Process
How many years of residency for full OAS?|10|20|40|50|2|40 years of residency since age 18 for full pension.|Ch 8: Retirement
What is a 'Stop-Loss' in health insurance?|The max payout|The max out-of-pocket for the client|The deductible|The end date|1|Client pays up to the stop-loss, then insurer pays 100%.|Ch 9: Insurance
Which investment has the highest seniority?|Common Shares|Preferred Shares|Mortgage Bonds|Debentures|2|Secured bonds (Mortgage bonds) are paid first.|Ch 7: Investments
What is 'Real' GDP?|GDP with all sectors|GDP adjusted for inflation|GDP before tax|GDP of housing|1|Real GDP accounts for inflation.|Ch 2: Economics
Which 'Trust' is in a Will?|Inter Vivos|Testamentary|Family|Revocable|1|Testamentary trusts are triggered by death.|Ch 10: Estate
If you lose 50%, what gain is needed to break even?|50%|75%|100%|200%|2|100% gain to recover a 50% loss.|Ch 7: Investments
What is the inclusion for 'Interest' income?|0%|50%|75%|100%|3|Interest is 100% taxable.|Ch 4: Taxation
Which document handles 'Property' while alive?|Will|Property POA|Personal Care POA|Executor|1|POA Property handles finances during life.|Ch 10: Estate
Which 'Indicator' is unemployment?|Leading|Lagging|Coincident|Predictive|1|Unemployment is a lagging indicator.|Ch 2: Economics
What is the 'Federal' bottom tax rate 2026?|10%|14%|15%|20%|1|For 2026, the lowest federal bracket is 14%.|Ch 4: Taxation
What is the 'Stress Test' for 4% contract?|4%|5.25%|6%|8%|2|Higher of 5.25% or contract+2% (4+2=6%).|Ch 3: Mortgages
Which 'Stage' is Step 1?|Gather|Establish Relationship|Analyze|Implement|1|Step 1 is establishing the relationship.|Ch 1: Process
A client wins $10,000 on a scratch ticket. Tax?|100% taxable|50% taxable|Tax-free|30% withholding|2|Lottery wins are tax-free in Canada.|Ch 4: Taxation
What is the max age to contribute to RRSP?|65|69|71|75|2|By Dec 31 of age 71.|Ch 8: Retirement`;
